### ISSUE TITLE
"undefined symbol: bitcoinconsensus_verify_script" on npm start

### ISSUE THREAD

**Issue by Yoyek** [bitpay/bitcore-node#115]
Hi, I have installed bitcore-node successfully on Ubuntu 14.04 server using instructions from README.md

But when I start with "npm start" i got:

```

> bitcore-node@0.2.0-dev start /home/btc/apps/bitcore-node
> node bin/start.js

/home/btc/apps/bitcore-node/node_modules/bindings/bindings.js:83
        throw e
              ^
Error: /home/btc/apps/bitcore-node/build/Release/bitcoind.node: undefined symbol: bitcoinconsensus_verify_script
    at Error (native)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at bindings (/home/btc/apps/bitcore-node/node_modules/bindings/bindings.js:76:44)
    at Object.<anonymous> (/home/btc/apps/bitcore-node/lib/daemon.js:4:35)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)

npm ERR! Linux 3.16.0-45-generic
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "start"
npm ERR! node v0.12.7
npm ERR! npm  v2.11.3
npm ERR! code ELIFECYCLE
npm ERR! bitcore-node@0.2.0-dev start: `node bin/start.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the bitcore-node@0.2.0-dev start script 'node bin/start.js'.
npm ERR! This is most likely a problem with the bitcore-node package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node bin/start.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls bitcore-node
npm ERR! There is likely additional logging output above.
```

**Comment by kleetus** [comment]
hi Yoyek: We've been in pretty active development with this. Try pulling the latest from master or the tag 0.2.0-beta.1. My guess is that you caught a commit that was not resolving all symbols correct during compilation of the bindings.

**Comment by Yoyek** [comment]
Thanks!

But I have this problem with v0.2.0-beta.1 also.
 
(Cloned repo from scratch. Then `git checkout v0.2.0-beta.1`, and `npm install` - with installation success status. Then I go this error when hit `npm start`)

Should I attach my npm-debug.log?

**Comment by braydonf** [comment]
Running `nm` shows that the symbol is undefined here, however `npm start` works:
```bash
~/bitcore-node(master)$ nm build/Debug/bitcoind.node | grep bitcoinconsensus_verify_script
                 U bitcoinconsensus_verify_script
```
I believe the only place we're using this is at: https://github.com/bitpay/bitcore-node/blob/master/lib/transaction.js#L110 However the method may not be necessary with some of the recent bindings for querying and events for transactions.

**Comment by kleetus** [comment]
I bet the dynamic linker is kicking in and finding this symbol for me on my machine, whereas on a fresh machine, this isn't the case. Great catch, repairing and/or removing the verify script because it just isn't needed at the moment.

**Comment by braydonf** [comment]
Running `nm` against latest master https://github.com/bitpay/bitcore-node/commit/d7c16e11a3988c9f0f9d90b907cce9929841696f no longer mentions the undefined symbol, and this should be resolved.

**Comment by Yoyek** [comment]
Thanks, it's working now!
