### ISSUE TITLE
dockerfile

### ISSUE THREAD

**Issue by braydonf** [bitpay/bitcore-node#122]
Copying this issue over from bitcoind.js:

> i tried setting it up on my Mac but had some issues, and I don't want to make this a forum for debugging my build. Could you provide a Dockerfile? Thanks!

https://github.com/bitpay/bitcoind.js/issues/59

**Comment by Levino** [comment]
We have one working here: https://github.com/satoshipay/insight-api-docker

**Comment by Levino** [comment]
This could be a base for it: https://github.com/satoshipay/insight-api-docker

Probably needs more configuration of services through environment ports.

Attention: The develop branch uses a patched bitcore-node.

**Comment by braydonf** [comment]
I believe this was added as part of the [bitcore](https://github.com/bitpay/bitcore) repository.
