### ISSUE TITLE
Run bitcoin tests against bitcore-node on travis

### ISSUE THREAD

**Issue by braydonf** [bitpay/bitcore-node#124]
Copying over from the bitcore issue:

> bitcore should
> - have a pull tester robot, for each new commit, just like Bitcoin Core
> - pass all the tests that Bitcoin Core has in the pulltester

https://github.com/bitpay/bitcore/issues/255

**Comment by kleetus** [comment]
the BitcoinPullTester does not seem to be used anymore. I have not seen it posting messages into PR's for a while. It is possible that the tests that @TheBlueMatt has prepared are still relevant for us to use. I will need to check into the viability of this.

**Comment by TheBlueMatt** [comment]
Bitcoin Core moved entirely over to Travis, since it has proper github integration.

**Comment by kleetus** [comment]
@braydonf @pnagurny should I close this in lieu of some other kind of acceptance testing plan?

**Comment by braydonf** [comment]
Tests are running on https://github.com/bitpay/bitcoin
