### ISSUE TITLE
Add start_date for indexing addresses

### ISSUE THREAD

**Issue by kleetus** [bitpay/bitcore-node#143]
If you are running a bitcore-node only to host your Copay wallets it would be awesome to be able to indicate: `--start-date=2015-06-01` so it would index txs after that date in addresses, so the index space would be *much* smaller, maybe faster to index, and for a wallet created after that date it wont have any difference.

**Comment by braydonf** [comment]
The current bottleneck I believe is bandwidth of downloading the blockchain, creating the additional address index should now take less or equal amount of time.

**Comment by kleetus** [comment]
should I close this issue?
