### ISSUE TITLE
Push notifications from bitcoin core?

### ISSUE THREAD

**Issue by flip111** [bitpay/bitcore-node#153]
From the readme: _A Node.js module that adds a native interface to Bitcoin Core for querying information about the Bitcoin blockchain._

Querying sounds like the client has to initiate the request to see what is the state of certain things. Does that mean this software does not support push notifications from bitcoin core to the client? Right now i'm using PHP and i have to poll bitcoin core with JSON RPC to see if a transaction is confirmed. This means a worker is running continiously, which complicates things and is bad for performance as well.

**Comment by pnagurny** [comment]
We expose a socket.io interface where you can subscribe to notifications. We don't have push notification support right now, but that is a good idea which we will consider for the future.

**Comment by braydonf** [comment]
I think this is a great case for a customized service, community contributed?

**Comment by kleetus** [comment]
This is a perfect use case for the first service written on top of bitcore-node.

**Comment by braydonf** [comment]
Indeed, would make a good service, but may not necessary need to be a part of bitcore-node itself.
