### ISSUE TITLE
Reindexing Status

### ISSUE THREAD

**Issue by braydonf** [bitpay/bitcore-node#157]
Received these logs when reindexing with txindex:
```bash
Bitcoin Core Daemon New Height: 176063 Percentage: 1.5193864107131958
Bitcoin Core Daemon New Height: 176102 Percentage: 1.5208615064620972
Bitcoin Core Daemon New Height: 176141 Percentage: 1.5221902132034302
Bitcoin Core Daemon New Height: 176186 Percentage: 1.5238778591156006
```

- The bitcore-node sync halted with a block not found error (since the index is needed), would it be better to pause syncing until the reindex is complete, and then resume?
- The percentage status indicates the reindex progress time estimate?
- The height indicates the last block indexed?

**Comment by kleetus** [comment]
just some notes for this task (for myself): 
1. if the user has the "reindex=1" in their bitcoin.conf, then we need to detect this fact and not start up the other modules
2. once the reindex is finished and bitcore-node is restarted, then we can resume the operation.

**Comment by braydonf** [comment]
Address in https://github.com/bitpay/bitcore-node/pull/193
