### ISSUE TITLE
Fix regtest: "will get an event when the tip is new"

### ISSUE THREAD

**Issue by braydonf** [bitpay/bitcore-node#164]
Test will randomly fail because of the way that events for tips are announced, e.g. every second (instead of exactly when the tip changes:
```
  1) Daemon Binding Functionality tip updates will get an event when the tip is new:
      + expected - actual
      +151
      -150
      at Daemon.<anonymous> (/home/travis/build/bitpay/bitcore-node/integration/regtest.js:260:23)
      at Daemon.emit (events.js:107:17)
      at onTipUpdateListener (/home/travis/build/bitpay/bitcore-node/lib/daemon.js:74:16)
```

https://travis-ci.org/bitpay/bitcore-node/builds/77703908

**Comment by kleetus** [comment]
this is no longer a issue (I think), the tests aren't failing for me or for Travis lately and the tips are not announced every second, but instead they are announced when they happen using a callback.

**Comment by braydonf** [comment]
It's sleeping: https://github.com/bitpay/bitcore-node/blob/master/src/libbitcoind.cc#L396 However I think that is okay because when there are lot of new blocks having a callback or each may be too much.

**Comment by braydonf** [comment]
Fixed in: https://github.com/bitpay/bitcore-node/pull/201
