### ISSUE TITLE
BWS Service - First iteration

### ISSUE THREAD

**Issue by pnagurny** [bitpay/bitcore-node#172]

**Comment by braydonf** [comment]
- Continue from PR https://github.com/bitpay/bitcore-wallet-service/pull/314/files
- Add a "bitcoreNode" service to start/stop the wallet service, and add the `/bws/api/` route to the main express application.
- Include as part of the default configuration

**Comment by braydonf** [comment]
See: https://github.com/bitpay/bitcore-wallet-service/pull/351
