### ISSUE TITLE
error when closing while reindexing

### ISSUE THREAD

**Issue by braydonf** [bitpay/bitcore-node#218]
```
bitcore-node: bitcore-node/bin/../libbitcoind/depends/x86_64-linux/include/boost/signals2/detail/lwm_pthreads.hpp:60: void boost::signals2::mutex::lock(): Assertion `pthread_mutex_lock(&m_) == 0' failed.
Aborted (core dumped)
```
Steps to reproduce:
1. Start up a node with the reindex flag set in bitcoin.conf
2. The node should only start up bitcoind
3. Press ctrl+c to exit, a Segmentation fault or the above error should be listed

**Comment by kleetus** [comment]
the issue with this is that:

when reindexing...the bitcoind service does not fully start up (its busy reindexing), in other words, the callback passed to bitcoind.start never gets called, therefore the service is not set to node services, therefore, when stop is called on the node, the bitcoind service is not running, ergo no reason to shut it down.

possible fixes:

the stop method on each service ought to know what state its in and handle a stop call even if its not already running, or loading, etc.

**Comment by braydonf** [comment]
We could possibly add a service into the node.services object while it's starting... and then stop will be called. However I don't know if it's a good idea to call stop on a process that hasn't yet started.

**Comment by braydonf** [comment]
Another option would be to have the start function watch for a "stopping" state on the node itself, and then stop trying to start, if that event happens.

**Comment by braydonf** [comment]
Fixed by: https://github.com/bitpay/bitcore-node/pull/231
