### ISSUE TITLE
I can't seem to get environmental variables working

### ISSUE THREAD

**Issue by rhoop** [bitpay/bitcore-node#25]
All config parameters seem to be read from config/default.yml. Nothing that is read by config.js is injected.

See below. Logging was added.

console.log(bitcoindConf);
```
$ node config.js
{ protocol: 'http',
  user: 'bituser',
  pass: 'testpass',
  host: '127.0.0.1',
  port: '18333',
  p2pPort: '18332',
  p2pHost: '127.0.0.1',
  dataDir: '/var/lib/bitcoindtestnet3',
  disableAgent: true }
```

```
$ node index.js
{ BitcoreNode: { NetworkMonitor: { network: 'livenet', host: 'localhost', port: 8333 } } }
Connection to bitcoind failed
```

**Comment by maraoz** [comment]
Hey @rhoop, `bitcore-node` is still under heavy development, and not ready for use yet. 
If you want to test things out though... you should edit `config/default.yml`. That's the new config system. I'll remove the old config file in a PR now: https://github.com/bitpay/bitcore-node/pull/27

**Comment by rhoop** [comment]
Thanks @maraoz. Is there any documentation for the new config system?

**Comment by carnesen** [comment]
I removed the environment variable stuff from the readme and added a brief note that the configuration files are written in yaml. https://github.com/carnesen/bitcore-node/commit/3e479a7738516fdaa2de234115cdd3339bb79d66

**Comment by aasheikh** [comment]
This is still an issue. see below with the console log
console.log(config) 


'''
$ node  index.js 
{ BitcoreNode: { NetworkMonitor: { network: 'testnet', host: '127.0.0.1', port: 18333 } },
  Reporter: 'simple',
  LevelUp: './db',
  RPC: 
   { user: 'bitcoinrpc',
     pass: 'bitcoinpassword',
     protocol: 'http',
     host: '127.0.0.1',
     port: 18332 } }

Connection to bitcoind failed
'''

**Comment by carnesen** [comment]
@aasheikh I can see from the console output that the program is picking up your config values, so I don't think this GitHub issue is the source of your problem. "Connection to bitcoind failed" actually means "connection refused" which usually means the wrong port or host has been provided. Perhaps try connecting to that host:port combination using a simpler program like curl or the command-line interface included with Bitcoin Core.

**Comment by aasheikh** [comment]
Without changing anything in in my .bitcoin/bitcoin.conf   

I have switched back to insight with following env variable set and the connection was successful . 

export BITCOIND_USER=bitcoinrpc
export BITCOIND_PASS=bitcoinpassword
export INSIGHT_NETWORK=testnet
INSIGHT_FORCE_RPC_SYNC=1
.
.
info: insight server listening on port 3001 in development mode

info: status: [100%]
{ '0': 'connecting to 127.0.0.1:18333' }
{ '0': 'connected to 127.0.0.1:18333' }


bitcore-node is still failing: 
'

$ node index.js 
{ BitcoreNode: { NetworkMonitor: { network: 'testnet', host: '127.0.0.1:18333' } },
  Reporter: 'simple',
  LevelUp: './db',
  RPC: 
   { user: 'bitcoinrpc',
     pass: 'bitcoinpassword',
     protocol: 'http',
     host: '127.0.0.1',
     port: 18332 } }
Connection to bitcoind failed
$

**Comment by aasheikh** [comment]
Below changes  fixed my connection issue. It seems the properties are not set in Peer object. But there is still issue with "INVALID MESSAGESTART version peer=16" error message in bitcond log file

Index: lib/networkmonitor.js
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- lib/networkmonitor.js	(revision fc8f53372a73236cbe1f8a1061df3dc9245d8848)
+++ lib/networkmonitor.js	(revision )
@@ -25,6 +25,9 @@
   var host = opts.host || 'localhost';
   var port = opts.port || Networks.defaultNetwork.port;
   var peer = new Peer(host, port, network);
+  peer.host = host;
+  peer.port = port;
+  peer.network = network;
   return new NetworkMonitor(eventBus, peer);
 };

**Comment by maraoz** [comment]
@aasheikh thanks for reporting what fixed it for you. It looks strage that Peer is not setting the options correcly, though. I think it may be related to using an incorrect version of `bitcore-p2p`, for some strange reason. I'll check it.

Regarding "INVALID MESSAGESTART version peer=16", are you using this for an altcoin? That's sounds like some errors reported by altcoin developers

**Comment by aasheikh** [comment]
@maraoz  No I am using  bitcoind/ bitcoin-qt

**Comment by braydonf** [comment]
Mostly outdated with current development.
