### ISSUE TITLE
Common-blockchain compliance

### ISSUE THREAD

**Issue by dcousens** [bitpay/bitcore-node#26]
A collection of other bitcoin related developers and I have been iterating on a [common-blockchain](https://github.com/dcousens/common-blockchain) API standard in terms of available end points for block explorers.
It is a standard to provide complete informational representations of various objects on the blockchain, without compromise, and is easily testable.

The aim of this is to provide an API that could be easily hot-swapped if a service goes down or is overloaded.

Naturally this API is open to change, and we're very open to feedback as to the end points that are currently provided.  It'd be great if you would be open to iterating on this with us such that 'swapping' out block explorers for web services is dead-simple in the future.

Below is a list of common-blockchain repositories, many of them are simple wrappers, but they each have several pain points due to missing information or missing end points, not provided by the block explorers themselves.

https://github.com/weilu/cb-blockr
https://github.com/dcousens/cb-node - a pure API implementation, the ideal case
https://github.com/dcousens/cb-chain
https://github.com/dcousens/cb-helloblock
https://github.com/jprichardson/cb-insight

**Comment by dcousens** [comment]
To be clear, this doesn't mean offerring only what is provided in the common-blockchain spec.  But it would be nice if that spec was a sub-set of your given API.

**Comment by maraoz** [comment]
We're considering your spec with @eordano. We'll probably implement it as a different version of the API, so you'll have:
`explorer.bitcore.io/cb/...`
`explorer.bitcore.io/v1/...`
`explorer.bitcore.io/v2/...`

**Comment by dcousens** [comment]
@maraoz I think that is a sane approach.

**Comment by matiu** [comment]
+1

We have the same at BWS.

On Wed, Mar 18, 2015 at 9:12 AM, Daniel Cousens <notifications@github.com>
wrote:

> @maraoz <https://github.com/maraoz> I think that is a sane approach.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bitpay/bitcore-node/issues/26#issuecomment-82941253>.
>



-- 
BitPay.com

**Comment by jprichardson** [comment]
Would love to see this! @maraoz @eordano let us know what we can do to help shape the spec so that it makes sense for both providers and consumers :)

**Comment by dcousens** [comment]
@matiu did you mean for BWS you have this need, or you already have something similar in place?
