### ISSUE TITLE
ARM binary builds for distribution

### ISSUE THREAD

**Issue by braydonf** [bitpay/bitcore-node#260]
Many embedded devices built specifically for running a full node use ARM. Node.js 4 is also distributing builds for ARM, which will help.

**Comment by kleetus** [comment]
I closed my PR for this

**Comment by braydonf** [comment]
We can likely revisit feasibility of this once mempool limiting is available, to keep the memory footprint small: https://github.com/bitcoin/bitcoin/pull/6722
