### ISSUE TITLE
Abort trap 6 after recompiling

### ISSUE THREAD

**Issue by pnagurny** [bitpay/bitcore-node#278]
After recompiling ( `node-gyp rebuild`) I will oftentimes get an Abort trap 6 the first time I run bitcore node. Every time after it starts successfully.

```
node bin/start.js 
{bitcore-node} info: Starting bitcoind
Assertion failed: (handle->type == UV_TCP || handle->type == UV_TTY || handle->type == UV_NAMED_PIPE), function uv___stream_fd, file ../deps/uv/src/unix/stream.c, line 1535.
Abort trap: 6
```

**Comment by kleetus** [comment]
I "think" this is related to #351. I think if this were solved, the other would be too

**Comment by braydonf** [comment]
No longer relevant
