### ISSUE TITLE
Run a Full Node Guide

### ISSUE THREAD

**Issue by braydonf** [bitpay/bitcore-node#279]
A guide to setup a full node, configure with different networks, and other useful information.

**Comment by braydonf** [comment]
https://gist.github.com/braydonf/a83d653f57aa3391d2b8

**Comment by ChesTaylor** [comment]
There is a typo in Step 3:

The line 
`bitcore-node -d <path-to-datadirectory> mynode` 
should read
`bitcore-node create -d <path-to-datadirectory> mynode`

Also, Step 7 should read:
`bitcore-node install insight-api insight-ui`
rather than:
`bitcore-node add insight-api insight-ui`

**Comment by ChesTaylor** [comment]
Still a very helpful guide, thank you very much for writing it!

**Comment by braydonf** [comment]
Thanks, I think these have been fixed and now at: https://bitcore.io/guides/full-node

**Comment by ChesTaylor** [comment]
Thank you very much!
