### ISSUE TITLE
missed openssl-1.0.1k.tar.gz

### ISSUE THREAD

**Issue by phplaboratory** [bitpay/bitcore-node#282]
https://bitcoincore.org/depends-sources/openssl-1.0.1k.tar.gz:
2015-10-03 11:40:47 ERROR 404: Not Found.

**Comment by kleetus** [comment]
Thanks for bringing this to our attention. Currently, indeed, that tarball URL yields a 404. I suspected that bitcoin core had upgraded openssl and linked to a newer version (fingers crossed), but that was not the case. I will hit up the admin to that site.

**Comment by kleetus** [comment]
The link you specified, indeed, isn't available from bitcoincore.org. When you try and build bitcore-node from source by running, "npm install" (and you don't reference a beta build in package.json), then our build scripts should run "make" inside the depends directory inside libbitcoind. This should try and download openssl from https://www.openssl.org/source/openssl-1.0.1k.tar.gz. Where are you seeing this url?

**Comment by phplaboratory** [comment]
by mistake I am demanged ssh library for wget, and thats why it was trying to download from https://bitcoincore.org/ , its set it as reserve source of files. Thats how I am came there.
