### ISSUE TITLE
migrate cli commands to bitcore

### ISSUE THREAD

**Issue by braydonf** [bitpay/bitcore-node#291]
Task list:
- [ ] Add stop CLI command
- [ ] Fix error with CLI command https://github.com/bitpay/bitcore-node/issues/281
- [ ] Improve "add" command to consider case that a service has already been added.
- [ ] Commands are not validated (give an error if a command doesn't exist).
- [ ] Migrate command to bitcore
- [ ] Update bitcore README with the cli commands

**Comment by hyzhak** [comment]
:+1: for stop command!

**Comment by braydonf** [comment]
Closing, since the CLI commands in bitcore-node I think make sense.

@hyzhak using upstart and commands such as, work well:
```
$ service bitcored start
$ service bitcored restart
$ service bitcored stop
```
