### ISSUE TITLE
Bus issue

### ISSUE THREAD

**Issue by unusualbob** [bitpay/bitcore-node#298]
https://github.com/bitpay/bitcore-node/blob/v0.2.0-beta.10/docs/bus.md

This lists the event 'transaction' as being supported, but I cannot get events from it. I suspect this was early documentation and is just incorrect. These were my results:

```js
  bus.on('db/transaction', function(tx) {
    console.log('dbtx!'); //results in 'dbtx!'
  });

  node.services.bitcoind.on('tx', function(txInfo) {
    console.log('btctx!'); //results in 'btctx!'
  });

  bus.on('transaction', function(tx) {
    console.log('tx'); //Never gets fired :(
  });
```

**Comment by braydonf** [comment]
Yep, the transaction event moved to db/transaction. Several services may have transaction event, so a namespace was added.
