### ISSUE TITLE
Multiple instances of bitcore

### ISSUE THREAD

**Issue by unusualbob** [bitpay/bitcore-node#308]
When trying to use bitcore-node as a dependency, I am required to delete its copy of bitcore in order to use bitcore in my own code as bitcore will detect the duplicate instances of itself and prevent startup. One possible solution could be exposing bitcore from bitcore-node.

**Comment by braydonf** [comment]
It's common to run into this, and can be avoided with a `package.json` similar to (where each dependency requires the `0.13.x` range of bitcore):

```json
dependencies: {
  "bitcore": "^0.13.4",
  "bitcore-ecies": "^0.12.0",
  "bitcore-payment-protocol": "^0.13.0",
  "bitcore-mnemonic": "^0.13.2",
  "bitcore-node": "^0.2.0-beta.10",
}
```

Exposing bitcore instead of at the package.json level could lead to other issues later for other modules that also depend on it.

**Comment by unusualbob** [comment]
I have the same version of bitcore in both, but it blocks me.

```Error: More than one instance of bitcore found with versions: v0.13.4 and v0.13.4. Please make sure to require bitcore and check that submodules do not also include their own bitcore dependency.```

**Comment by braydonf** [comment]
The error message could be improved, the same version with multiple instances can still cause other issues later because of `instanceof` type handling and the network object operates as a singleton.

**Comment by braydonf** [comment]
Also related issue: https://github.com/bitpay/bitcore/issues/1328
