### ISSUE TITLE
Event for all transactions

### ISSUE THREAD

**Issue by unusualbob** [bitpay/bitcore-node#311]
Currently the bitcoind tx event does not emit events for transactions that were rejected from the mempool. I'd like to request an event for transactions that were rejected (or just all txs), a bonus would be the reason they were rejected.

Currently there is no way to detect double spend txs or malleated txs because of this.

**Comment by braydonf** [comment]
This may be a use case for bitcore-p2p that connects directly with any peer.

**Comment by braydonf** [comment]
Related: https://github.com/bitpay/bitcore-node/issues/304
