### ISSUE TITLE
Don't throw errors from within api methods for validation errors

### ISSUE THREAD

**Issue by pnagurny** [bitpay/bitcore-node#313]
Any method that is exposed externally should not throw validation errors, but instead call the callback with the error. This way bitcore node doesn't crash when api methods are ran with bad data!

**Comment by braydonf** [comment]
- getOutputs `_.isObject()`: https://github.com/bitpay/bitcore-node/blob/master/lib/services/address/index.js#L909

- getInputForOutput `_.isNumber()`: https://github.com/bitpay/bitcore-node/blob/master/lib/services/address/index.js#L740

- getInputForOutput `_.isObject()`: https://github.com/bitpay/bitcore-node/blob/master/lib/services/address/index.js#L741

**Comment by braydonf** [comment]
Validation errors are not thrown anylonger.
