### ISSUE TITLE
Build dependencies if they're not compatible

### ISSUE THREAD

**Issue by wzrdtales** [bitpay/bitcore-node#327]
Currently it is not possible to build and use bitcore node on Systems that do not have GLIBC 2.15. I need to manually manipulate the version to something that can't be found, so that it compiles instead of downloading.

```
/lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.15' not found
```

**Comment by kleetus** [comment]
that is a good point. We are pretty selective about which hosts we provide binaries to. This will change very soon. Thanks for the issue.

**Comment by braydonf** [comment]
No longer relevant as bitcoin is built with: https://github.com/bitpay/bitcoin/tree/0.12-bitcore
