### ISSUE TITLE
unconfirmedBalance is always equal to (confirmed) balance

### ISSUE THREAD

**Issue by ChesTaylor** [bitpay/bitcore-node#340]
After following [this guide](https://gist.github.com/braydonf/a83d653f57aa3391d2b8) to set up bitcore-node with Insight, I queried the Insight API for information about a testnet address with some funds in it from a while back:

```
$ curl localhost:3001/insight-api/addr/2N67p3V4ns1YW99rELo7NRBji2VLnfHUNeF
{"addrStr":"2N67p3V4ns1YW99rELo7NRBji2VLnfHUNeF","balance":0.001,"balanceSat":100000,"totalReceived":0.001,"totalReceivedSat":100000,"totalSent":0,"totalSentSat":0,"unconfirmedBalance":0.001,"unconfirmedBalanceSat":100000,"unconfirmedTxApperances":0,"txApperances":1,"transactions":["73ee3be1ffb2915414a432927dc059c7b0174f97cd71248782ad776870cbcf73"]}
```

Note that even though `unconfirmedTxApperances` [sic.] is 0, `unconfirmedBalance` and `unconfirmedBalanceSat` are non-zero. Some experimentation determined that for any address I query, the `unconfirmedBalance` and `unconfirmedBalanceSat` are always equal to the `balance` and `balanceSat`, respectively.

This is true for addresses which had funds in them prior to running bitcore-node and addresses that received funds which confirmed while bitcore-node was running.

The same query run using bitcoind version 0.11.1 and Insight version 0.2.18 returned the following results:

```
$ curl localhost:3001/api/addr/2N67p3V4ns1YW99rELo7NRBji2VLnfHUNeF
{"addrStr":"2N67p3V4ns1YW99rELo7NRBji2VLnfHUNeF","balance":0.001,"balanceSat":100000,"totalReceived":0.001,"totalReceivedSat":100000,"totalSent":0,"totalSentSat":0,"unconfirmedBalance":0,"unconfirmedBalanceSat":0,"unconfirmedTxApperances":0,"txApperances":1,"transactions":["73ee3be1ffb2915414a432927dc059c7b0174f97cd71248782ad776870cbcf73"]}
```

In those results, the `unconfirmedBalance` and `unconfirmedBalanceSat` display correctly.

**Comment by pnagurny** [comment]
Thanks for the feedback! You're right - there does appear to be a discrepancy. `unconfirmedBalance` shouldn't include the confirmed balance. We are working on a PR (#341) to address this.

**Comment by ChesTaylor** [comment]
After updating to bitcore-node v0.2.5, the following results were returned from Insight:

```
$ curl localhost:3001/insight-api/addr/2N67p3V4ns1YW99rELo7NRBji2VLnfHUNeF
{"addrStr":"2N67p3V4ns1YW99rELo7NRBji2VLnfHUNeF","balance":0.001,"balanceSat":100000,"totalReceived":0.001,"totalReceivedSat":100000,"totalSent":0,"totalSentSat":0,"unconfirmedBalance":0,"unconfirmedBalanceSat":0,"unconfirmedTxApperances":0,"txApperances":1,"transactions":["73ee3be1ffb2915414a432927dc059c7b0174f97cd71248782ad776870cbcf73"]}
```

`unconfirmedBalance` and `unconfirmedBalanceSat` correctly show as 0.

Thanks for the prompt fix :n)

**Comment by Levino** [comment]
I think this is a non-fix. What is the verbal definition of the unconfirmed balance?

**Comment by ChesTaylor** [comment]
"Unconfirmed balance" should be the part of an address' funds with 0 confirmations. It should be distinct from the confirmed balance, which would be the part of an address' funds with 1 or more confirmations. 

Based on those guidelines, the fix worked.
