### ISSUE TITLE
Include build details for running on CentOS

### ISSUE THREAD

**Issue by braydonf** [bitpay/bitcore-node#361]
As well as make sure that it will run correctly.

**Comment by rromanchuk** [comment]
+1 lots of users running aws default linux ami.  bitcoind is a huge pain in the ass to build because the removal of elliptical curves on their openssl package. You guys have a pretty robust build, but i bet there are hiccups. I'll give it a try later today to see how far i get

**Comment by rromanchuk** [comment]
https://aws.amazon.com/amazon-linux-ami/  that would be great testing environment

**Comment by kreshendo** [comment]
any updates on installing bitcore on centos? i'm stuck right now.

**Comment by braydonf** [comment]
Installing on CentOS should work as expected.
