### ISSUE TITLE
leveldown install Ubuntu

### ISSUE THREAD

**Issue by julian-smith-code** [bitpay/bitcore-node#362]
Now using node v4.2.2 (npm v2.14.7)
root@live:~# npm install -g bitcore-node
 
> bufferutil@1.2.1 install /root/.nvm/versions/node/v4.2.2/lib/node_modules/bitcore-node/node_modules/socket.io-client/node_modules/engine.io-client/node_modules/ws/node_modules/bufferutil
> prebuild --download

sh: 1: prebuild: Permission denied
 
> leveldown@1.4.2 install /root/.nvm/versions/node/v4.2.2/lib/node_modules/bitcore-node/node_modules/leveldown
> prebuild --download

sh: 1: prebuild: Permission denied
npm WARN optional dep failed, continuing bufferutil@1.2.1
 
> utf-8-validate@1.2.1 install /root/.nvm/versions/node/v4.2.2/lib/node_modules/bitcore-node/node_modules/socket.io-client/node_modules/engine.io-client/node_modules/ws/node_modules/utf-8-validate
> prebuild --download

sh: 1: prebuild: Permission denied
npm WARN optional dep failed, continuing utf-8-validate@1.2.1
-
> bufferutil@1.2.1 install /root/.nvm/versions/node/v4.2.2/lib/node_modules/bitcore-node/node_modules/socket.io/node_modules/engine.io/node_modules/ws/node_modules/bufferutil
> prebuild --download

sh: 1: prebuild: Permission denied

> utf-8-validate@1.2.1 install /root/.nvm/versions/node/v4.2.2/lib/node_modules/bitcore-node/node_modules/socket.io/node_modules/engine.io/node_modules/ws/node_modules/utf-8-validate
> prebuild --download

sh: 1: prebuild: Permission denied
npm WARN optional dep failed, continuing bufferutil@1.2.1
npm WARN optional dep failed, continuing utf-8-validate@1.2.1

> utf-8-validate@1.2.1 install /root/.nvm/versions/node/v4.2.2/lib/node_modules/bitcore-node/node_modules/socket.io/node_modules/socket.io-client/node_modules/engine.io-client/node_modules/ws/node_modules/utf-8-validate
> prebuild --download

sh: 1: prebuild: Permission denied

> bufferutil@1.2.1 install /root/.nvm/versions/node/v4.2.2/lib/node_modules/bitcore-node/node_modules/socket.io/node_modules/socket.io-client/node_modules/engine.io-client/node_modules/ws/node_modules/bufferutil
> prebuild --download

sh: 1: prebuild: Permission denied
npm WARN optional dep failed, continuing utf-8-validate@1.2.1
npm WARN optional dep failed, continuing bufferutil@1.2.1
npm ERR! Linux 3.13.0-65-generic
npm ERR! argv "/root/.nvm/versions/node/v4.2.2/bin/node" "/root/.nvm/versions/node/v4.2.2/bin/npm" "install" "-g" "bitcore-node"
npm ERR! node v4.2.2
npm ERR! npm  v2.14.7
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn

npm ERR! leveldown@1.4.2 install: `prebuild --download`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the leveldown@1.4.2 install script 'prebuild --download'.
npm ERR! This is most likely a problem with the leveldown package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     prebuild --download
npm ERR! You can get their info via:
npm ERR!     npm owner ls leveldown
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /root/npm-debug.log
root@live:~#

**Comment by julian-smith-code** [comment]
And.. nice variation if taking download and build option:

root@live:/var/local/bitcore-node# npm install
-
> bufferutil@1.2.1 install /var/local/bitcore-node/node_modules/socket.io/node_modules/engine.io/node_modules/ws/node_modules/bufferutil
> prebuild --download


> bufferutil@1.2.1 install /var/local/bitcore-node/node_modules/socket.io-client/node_modules/engine.io-client/node_modules/ws/node_modules/bufferutil
> prebuild --download


> utf-8-validate@1.2.1 install /var/local/bitcore-node/node_modules/socket.io-client/node_modules/engine.io-client/node_modules/ws/node_modules/utf-8-validate
> prebuild --download

 
> utf-8-validate@1.2.1 install /var/local/bitcore-node/node_modules/socket.io/node_modules/engine.io/node_modules/ws/node_modules/utf-8-validate
> prebuild --download

/
> utf-8-validate@1.2.1 install /var/local/bitcore-node/node_modules/socket.io/node_modules/socket.io-client/node_modules/engine.io-client/node_modules/ws/node_modules/utf-8-validate
> prebuild --download


> bufferutil@1.2.1 install /var/local/bitcore-node/node_modules/socket.io/node_modules/socket.io-client/node_modules/engine.io-client/node_modules/ws/node_modules/bufferutil
> prebuild --download

npm WARN cannot run in wd bitcore-node@1.0.0-dev ./bin/install (wd=/var/local/bitcore-node)
socket.io-client@1.3.7 node_modules/socket.io-client
├── component-emitter@1.2.0
├── to-array@0.1.3
├── indexof@0.0.1
├── component-bind@1.0.0
├── backo2@1.0.2
├── object-component@0.0.3
├── debug@2.1.3 (ms@0.7.0)
├── has-binary@0.1.6 (isarray@0.0.1)
├── socket.io-parser@2.2.4 (isarray@0.0.1, debug@0.7.4, component-emitter@1.1.2, json3@3.2.6)
├── parseuri@0.0.2 (better-assert@1.0.2)
└── engine.io-client@1.5.4 (component-inherit@0.0.3, has-cors@1.1.0, component-emitter@1.1.2, xmlhttprequest-ssl@1.5.1, parsejson@0.0.1, parseqs@0.0.2, parseuri@0.0.4, engine.io-parser@1.2.2, ws@0.8.0)

socket.io@1.3.7 node_modules/socket.io
├── debug@2.1.3 (ms@0.7.0)
├── has-binary@0.1.6 (isarray@0.0.1)
├── socket.io-adapter@0.3.1 (debug@2.2.0, socket.io-parser@2.2.2)
├── socket.io-parser@2.2.4 (isarray@0.0.1, debug@0.7.4, component-emitter@1.1.2, json3@3.2.6)
├── engine.io@1.5.4 (base64id@0.1.0, accepts@1.1.4, engine.io-parser@1.2.2, ws@0.8.0)
└── socket.io-client@1.3.7 (component-emitter@1.2.0, to-array@0.1.3, indexof@0.0.1, component-bind@1.0.0, backo2@1.0.2, object-component@0.0.3, parseuri@0.0.2, engine.io-client@1.5.4)
root@live:/var/local/bitcore-node# npm start

> bitcore-node@1.0.0-dev start /var/local/bitcore-node
> node bin/start.js

module.js:338
    throw err;
          ^
Error: Cannot find module 'bitcoind/package.json'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Function.setupServices (/var/local/bitcore-node/lib/scaffold/start.js:51:30)
    at start (/var/local/bitcore-node/lib/scaffold/start.js:203:31)
    at Object.<anonymous> (/var/local/bitcore-node/bin/start.js:8:1)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)

npm ERR! Linux 3.13.0-65-generic
npm ERR! argv "/root/.nvm/versions/node/v0.12.7/bin/node" "/root/.nvm/versions/node/v0.12.7/bin/npm" "start"
npm ERR! node v0.12.7
npm ERR! npm  v2.11.3
npm ERR! code ELIFECYCLE
npm ERR! bitcore-node@1.0.0-dev start: `node bin/start.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the bitcore-node@1.0.0-dev start script 'node bin/start.js'.
npm ERR! This is most likely a problem with the bitcore-node package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node bin/start.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls bitcore-node
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /var/local/bitcore-node/npm-debug.log
root@live:/var/local/bitcore-node#

**Comment by posita** [comment]
I'm getting the same thing on Debian Jessie (via Docker) w/ node 4.2.2 installed via [`nodeenv`](https://ekalinin.github.io/nodeenv/):

```sh
root@1174a8b036d9:/# /opt/insight/bin/node --version
v4.2.2
root@1174a8b036d9:/# /opt/insight/bin/npm --version
2.14.7
root@1174a8b036d9:/# /opt/insight/bin/npm install -g bitcore-node
|
> bufferutil@1.2.1 install /opt/insight/lib/node_modules/bitcore-node/node_modules/socket.io/node_modules/engine.io/node_modules/ws/node_modules/bufferutil
> prebuild --download

sh: 1: prebuild: Permission denied

> utf-8-validate@1.2.1 install /opt/insight/lib/node_modules/bitcore-node/node_modules/socket.io-client/node_modules/engine.io-client/node_modules/ws/node_modules/utf-8-validate
> prebuild --download

sh: 1: prebuild: Permission denied
npm WARN optional dep failed, continuing bufferutil@1.2.1

> utf-8-validate@1.2.1 install /opt/insight/lib/node_modules/bitcore-node/node_modules/socket.io/node_modules/engine.io/node_modules/ws/node_modules/utf-8-validate
> prebuild --download

sh: 1: prebuild: Permission denied
npm WARN optional dep failed, continuing utf-8-validate@1.2.1

> utf-8-validate@1.2.1 install /opt/insight/lib/node_modules/bitcore-node/node_modules/socket.io/node_modules/socket.io-client/node_modules/engine.io-client/node_modules/ws/node_modules/utf-8-validate
> prebuild --download

sh: 1: prebuild: Permission denied
npm WARN optional dep failed, continuing utf-8-validate@1.2.1

> leveldown@1.4.2 install /opt/insight/lib/node_modules/bitcore-node/node_modules/leveldown
> prebuild --download

sh: 1: prebuild: Permission denied
npm WARN optional dep failed, continuing utf-8-validate@1.2.1

> bufferutil@1.2.1 install /opt/insight/lib/node_modules/bitcore-node/node_modules/socket.io-client/node_modules/engine.io-client/node_modules/ws/node_modules/bufferutil
> prebuild --download

sh: 1: prebuild: Permission denied

> bufferutil@1.2.1 install /opt/insight/lib/node_modules/bitcore-node/node_modules/socket.io/node_modules/socket.io-client/node_modules/engine.io-client/node_modules/ws/node_modules/bufferutil
> prebuild --download

sh: 1: prebuild: Permission denied
npm WARN optional dep failed, continuing bufferutil@1.2.1
npm WARN optional dep failed, continuing bufferutil@1.2.1
npm ERR! Linux 4.1.13-boot2docker
npm ERR! argv "/opt/insight/bin/node" "/opt/insight/bin/npm" "install" "-g" "bitcore-node"
npm ERR! node v4.2.2
npm ERR! npm  v2.14.7
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn

npm ERR! leveldown@1.4.2 install: `prebuild --download`
npm ERR! spawn ENOENT
npm ERR!
npm ERR! Failed at the leveldown@1.4.2 install script 'prebuild --download'.
npm ERR! This is most likely a problem with the leveldown package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     prebuild --download
npm ERR! You can get their info via:
npm ERR!     npm owner ls leveldown
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /npm-debug.log
```

Complete `npm-debug.log`: <https://gist.github.com/posita/3825f46c4f66d72d041a>.

**Comment by posita** [comment]
UPDATE: I'm not sure if this has anything to do with @julian-smith-code's problem, but mine was apparently solved by the following:

```sh
root@b85a6120bcc9:/# ls -al /opt/insight/
total 32
drwxr-s--- 8 bc   bc   4096 Nov 29 05:17 .
drwxr-xr-x 9 root root 4096 Nov 29 05:20 ..
drwxr-sr-x 2 bc   bc   4096 Nov 29 05:17 bin
drwxr-sr-x 3 bc   bc   4096 Nov 29 05:17 include
drwxr-sr-x 5 bc   bc   4096 Nov 29 05:17 lib
drwxr-sr-x 2 bc   bc   4096 Nov 29 04:28 local
drwxr-sr-x 5 bc   bc   4096 Nov 29 05:17 share
drwxr-sr-x 3 bc   bc   4096 Nov 29 04:56 src
root@b85a6120bcc9:/# which node
root@b85a6120bcc9:/# which npm
root@b85a6120bcc9:/# /opt/insight/bin/npm install -g bitcore-node
... # [failure as described above]
root@b85a6120bcc9:/# sudo -u bc -g bc /opt/insight/bin/npm install -g bitcore-node
... # [failure]
root@b85a6120bcc9:/# . /opt/insight/bin/activate
root@b85a6120bcc9:/# which node
/opt/insight/bin/node
root@b85a6120bcc9:/# which npm
/opt/insight/bin/npm
root@b85a6120bcc9:/# npm install -g bitcore-node
... # [failure]
root@b85a6120bcc9:/# sudo -u bc -g bc -s bash -c '. /opt/insight/bin/activate && npm install -g bitcore-node'
... # [SUCCESS!]
```

**Comment by shea256** [comment]
I'm getting a similar issue on an Ubuntu droplet on Digital Ocean.

@posita how did you get set up with that /opt/insight folder?

And I think the fundamental issue here might be the fact that we're using `nvm`. Would you say that's correct?

@braydonf @kleetus have you run into anything like this? And do you have any plans to support node 5?  It seems that one of the barriers to node 5 support is an upgrade of `graceful-fs`.

**Comment by braydonf** [comment]
Are you installing as root user? There may be `npm` [permission issues](https://github.com/npm/npm/issues/3497) when installing with `root`. 

Possibly related: https://github.com/bitpay/bitcore-node/issues/426

**Comment by shea256** [comment]
@braydonf I tried installing as both a root user and as a normal user. However, when I install as a normal user I don't have access to do `-g` global installs.

**Comment by braydonf** [comment]
You should be able to do `-g` installs as a user when using `nvm`, as it's global to the user.

**Comment by braydonf** [comment]
Re: Node.js 5 support: https://github.com/bitpay/bitcore-node/issues/394

**Comment by shea256** [comment]
OK thank you. I just realized that I was not in `nvm` with my non-root user. I enabled `nvm` and gave my new user sudo access and `npm install -g bitcore-node` was a success!

Now of course, I ran into another issue when doing `bitcore-node create mynode` :/

```
dev@blockstack-explorer-1:~$ bitcore-node create mynode
npm WARN deprecated graceful-fs@3.0.8: graceful-fs version 3 and before will fail on newer node releases. Please update to graceful-fs@^4.0.0 as soon as possible.

> utf-8-validate@1.2.1 install /home/dev/mynode/node_modules/bitcore-node/node_modules/socket.io/node_modules/engine.io/node_modules/ws/node_modules/utf-8-validate
> prebuild --download



/home/dev/.nvm/versions/node/v4.2.6/lib/node_modules/bitcore-node/lib/cli/main.js:42
          throw err;
          ^

Error: There was an error installing dependencies.
    at ChildProcess.<anonymous> (/home/dev/.nvm/versions/node/v4.2.6/lib/node_modules/bitcore-node/lib/scaffold/create.js:145:25)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at maybeClose (internal/child_process.js:821:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
```

**Comment by braydonf** [comment]
Looks like `npm` exited with a non zero exit code. Is there anything in `mynode`?

**Comment by shea256** [comment]
Yes here's what it contains:

```
total 1144
drwxrwxr-x  4 dev dev    4096 Apr 13 17:08 .
drwxr-xr-x 10 dev dev    4096 Apr 13 17:25 ..
-rw-rw-r--  1 dev dev     137 Apr 13 17:06 bitcore-node.json
drwxrwxr-x  2 dev dev    4096 Apr 13 17:06 data
drwxrwxr-x  4 dev dev    4096 Apr 13 17:06 node_modules
-rw-rw-r--  1 dev dev 1144332 Apr 13 17:08 npm-debug.log
-rw-rw-r--  1 dev dev     243 Apr 13 17:06 package.json
```

And when I run `bitcore-node install insight-api` I get the following:

```
dev@blockstack-explorer-1:~/mynode$ bitcore-node install insight-api
/home/dev/mynode/node_modules/bitcore-node/node_modules/bindings/bindings.js:91
  throw err
  ^

Error: Could not locate the bindings file. Tried:
 → /home/dev/mynode/node_modules/bitcore-node/node_modules/leveldown/build/leveldown.node
 → /home/dev/mynode/node_modules/bitcore-node/node_modules/leveldown/build/Debug/leveldown.node
 → /home/dev/mynode/node_modules/bitcore-node/node_modules/leveldown/build/Release/leveldown.node
 → /home/dev/mynode/node_modules/bitcore-node/node_modules/leveldown/out/Debug/leveldown.node
 → /home/dev/mynode/node_modules/bitcore-node/node_modules/leveldown/Debug/leveldown.node
 → /home/dev/mynode/node_modules/bitcore-node/node_modules/leveldown/out/Release/leveldown.node
 → /home/dev/mynode/node_modules/bitcore-node/node_modules/leveldown/Release/leveldown.node
 → /home/dev/mynode/node_modules/bitcore-node/node_modules/leveldown/build/default/leveldown.node
 → /home/dev/mynode/node_modules/bitcore-node/node_modules/leveldown/compiled/4.2.6/linux/x64/leveldown.node
    at bindings (/home/dev/mynode/node_modules/bitcore-node/node_modules/bindings/bindings.js:88:9)
    at Object.<anonymous> (/home/dev/mynode/node_modules/bitcore-node/node_modules/leveldown/leveldown.js:4:46)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/home/dev/mynode/node_modules/bitcore-node/lib/services/address/index.js:14:17)
    at Module._compile (module.js:410:26)
```

**Comment by braydonf** [comment]
What' is in `npm-debug.log`? 

If you run `npm install` in `mynode` do you get any errors?

**Comment by shea256** [comment]
Ah `npm-debug.log` is empty now.

And nothing happens when I do `npm install`.

I still have the same problem with `bitcore-node install insight-api`.

I'm running `bitcore-node start` right now successfully.

**Comment by braydonf** [comment]
I would remove the `node_modules` and run `npm install` in the `mynode` directory again. It looks like there was an issue when installing and downloading the bindings for leveldown.

**Comment by braydonf** [comment]
By the way `npm install -g bitcore` will include insight-api and insight-ui already, and should be a fast track installation option for that case:
- https://bitcore.io/start
- https://bitcore.io/guides/full-node
- https://bitcore.io/guides/upstart-daemon

---
Also, I just went through to verify that the the installation process is working, and on Ubuntu 12.04 as a user this went smoothly:
```
nvm install v4
npm install -g bitcore-node@latest
bitcore-node create mynode
cd mynode
bitcore-node install insight-api
```

**Comment by shea256** [comment]
ok thank you, I'll try that in a bit.

**Comment by braydonf** [comment]
Okay, let us know if there are an other issues.

For others that may run into similar issues, `package.json` install scripts and commands, including those that download prebuilt binaries or compile platform specific code, are run as the user specified by the npm config which defaults to "nobody" that leads to various permission issues when installing.

**Reference Docs**:
- https://docs.npmjs.com/misc/config#user 
- https://docs.npmjs.com/misc/scripts#user

**Solutions when using `npm`**:
- Use the `--unsafe-perm` flag
- Run `npm install` without root privileges
- Configure npm user that has the correct privileges

**Comment by shea256** [comment]
@braydonf thank you, your latest sequence worked great for me!

Although, I think there still may be a problem with the sequence listed here:
https://github.com/bitpay/insight-ui
