### ISSUE TITLE
Heavy disk usage when querying Bitcoin address balance.

### ISSUE THREAD

**Issue by EBTCoin** [bitpay/bitcore-node#375]
Is it normal to have heavy disk usage when querying a Bitcoin address balance?

I set insight-api up on VM before the bitcore-node addition and I didn't notice this much disk usage.

Is there a way to minimize the amount of disk use?

Thank you,
Jude

**Comment by braydonf** [comment]
The way that the balance, and address summary is currently returned is by looking up all associated inputs and outputs for the address and calculating the sum. We've discussed optimizing this as there are also memory issues related: https://github.com/bitpay/bitcore-node/issues/372

**Comment by braydonf** [comment]
There are caches now that should reduce disk usage when necessary.

**Comment by EBTCoin** [comment]
Braydon,

Any estimate on how much more disk space the MongoDB change will take?

I am running in a VM with limited disk space and I just want to make sure
I'll have plenty of room after a resync.

Thanks,
Jude

**Comment by braydonf** [comment]
MongoDB isn't used. However 200GB should be plenty of space.
