### ISSUE TITLE
Configuring services in bitcore-node.json

### ISSUE THREAD

**Issue by Levino** [bitpay/bitcore-node#378]
The first example here https://bitcore.io/api/service looks like this:
```
{
  "services": [
    "bitcoind", "db", "address", "insight-api"
  ]
}
```
How can I configure one of the sub-services. I need to do something like:
```
{
  "services": [
    "bitcoind", 
    "db",
    "address", 
    {
       "name": "insight-api",
       "config": {
               routePrefix: "foo"
           }
  ] 
}
```

The above does not work, as "services" is expected to be an array of strings (I get a clunkly error message that "[object Object]/package.json" could not be found :)

So is there any way to configure sub-services from the bitcore-node.json or do I have to start them all on my own ("programatically" as you say) in a script and run that via ```node script.js```

**Comment by braydonf** [comment]
You can add configuration to "servicesConfig":
```
{
  "services": [
    "bitcoind", 
    "db",
    "address", 
    "insight-api"
  ],
  "servicesConfig": {
    "insight-api":
       "routePrefix": "foo"
     }
  }
}
```

Related issue: https://github.com/bitpay/insight-api/issues/430

**Comment by Levino** [comment]
Thanks @braydonf ! Looking forward to the docs update.
