### ISSUE TITLE
FIXED in #383 - npm install fails when missing global git config

### ISSUE THREAD

**Issue by posita** [bitpay/bitcore-node#380]
```sh
% git clone https://github.com/bitpay/bitcore-node.git
...
% cd bitcore-node
% npm install -g
...
HEAD is now at 7e27892... Merge pull request #6975
../patch-bitcoin.sh /.../.nvm/versions/node/v4.2.2/lib/node_modules/bitcore-node/bin/../libbitcoind
Switched to a new branch 'libbitcoind-2015.12.18'
patching file config_me.sh
patching file configure.ac
patching file depends/hosts/linux.mk
patching file depends/packages/bdb.mk
patching file depends/packages/boost.mk
patching file src/Makefile.am
patching file src/bitcoind.cpp
patching file src/init.cpp
patching file src/init.h
patching file src/main.cpp
patching file src/net.cpp
patching file src/net.h
patching file src/txmempool.cpp

*** Please tell me who you are.

Run

  git config --global user.email "you@example.com"
  git config --global user.name "Your Name"

to set your account's default identity.
Omit --global to set the identity only in this repository.

fatal: empty ident name (for <bc@574e3f2df4c7.(none)>) not allowed
...
```

This, of course, can be  worked around by preempting the `npm install` command with the appropriate `git config --global` commands. However, since it's a build process internal to bitcore-node, it probably should not require the installer to set a global config for a one-off commit for an internal clone of the bitcoin core repo. For example, it is unusual for the installing user in a Docker container be required to have a meaningful global `git` configuration.

**Comment by posita** [comment]
This can be fixed by adding the appropriate *local* `git config` commands in either of these places:

* https://github.com/bitpay/bitcore-node/blob/382f30801521e016acbb3a6797bddfb1c9802970/bin/build#L141
* https://github.com/bitpay/bitcore-node/blob/e4b7f37805e7ab9d474303b0e1a9a62b3410bd42/bin/patch-bitcoin#L26

For example:

```sh
git config user.email bitcore_build@dummy.dom
git config user.name 'Bitcore Build'
```

Replace the values with whatever is appropriate.

**Comment by braydonf** [comment]
Interesting, I think we should give this try.

**Comment by braydonf** [comment]
Just realized that `git` is also required for installing the prebuilt binaries, since `socket.io` are installed from github repositories, making this necessary for not only for building from source installation.

**Comment by posita** [comment]
@braydonf, does this mean that `git` is required by `npm install bitcore-node`?

**Comment by braydonf** [comment]
Yes, it looks that way as `git` is a dependency of `npm` itself.

**Comment by posita** [comment]
Let me know if you want me to augment `README.md` as part of #383.
