### ISSUE TITLE
Build/install instructions are missing prerequisites

### ISSUE THREAD

**Issue by posita** [bitpay/bitcore-node#382]
See <https://github.com/bitpay/bitcore-node/blob/41eb1c19e16591c88796a0987b3e45818d6d82f4/docs/build.md#ubuntu-1404-unixlinux>. The instructions should likely include something like:

```sh
sudo apt-get install curl # or wget if you prefer
sudo apt-get install python
```

Probably needs #381.

**Comment by braydonf** [comment]
Is this still valid?
