### ISSUE TITLE
`npm install` plus `bitcore[-node] create` seems horribly inefficient

### ISSUE THREAD

**Issue by posita** [bitpay/bitcore-node#386]
I am admittedly not that familiar with `npm`, but after doing an `npm install -g bticore` (or an `npm install` from within a cloned `git` repository), it appears that executing `bitcore[-node] create [dir]` rebuilds many of the same packages and copies (or reinstalls) many, *many* files redundant with what were created/installed with the original `npm install` command.

Is this just "the way of things" with `npm`, or is there something else going on here?

**Comment by braydonf** [comment]
It's possible to use a default node with config location at `~/.bitcore` without running create, where running it isn't necessary.
