### ISSUE TITLE
Clarify `getAddressSummary` response ambiquity

### ISSUE THREAD

**Issue by braydonf** [bitpay/bitcore-node#391]
Several of the results returned from the `getAddressSummary` method have different possible interpretations:
- "unconfirmedBalance" : "confirmed balance + unconfirmed transactions" vs. "unconfirmed delta"
- "appearances" : "number of inputs/outputs" vs. "total transaction ids"
- "totalReceived" : "received from another address" vs. "received"

**Comment by Levino** [comment]
This was kinda solved, not? Now it looks that the unconfirmed balance can get negative. Makes no sense but one can work around from there and add "balance" and "unconfirmedBalance" to get what is interesting: the balance that everyone in the network agrees on.

Referencing https://github.com/bitpay/bitcore-node/issues/363
