### ISSUE TITLE
Doesn't work on Node.js 5.x.x

### ISSUE THREAD

**Issue by hyzhak** [bitpay/bitcore-node#394]
got error:
```
Error: Node.js version 5.3.0 is expected to be ^0.12 || ^4.2
```

**Comment by kleetus** [comment]
We plan on targeting the LTS version Node.js which is v4 although there isn't anything stopping you from adding ^5 and testing it

**Comment by braydonf** [comment]
Adding support for various different versions of Node.js should faster now without Node.js addon bindings. This may work, however is untested with 5. We can cover with Node.js 6 LTS testing is added: https://github.com/bitpay/bitcore-node/issues/448
