### ISSUE TITLE
missing node-gyp in dependecies

### ISSUE THREAD

**Issue by prusnak** [bitpay/bitcore-node#398]
Script [`bin/build`](https://github.com/bitpay/bitcore-node/blob/master/bin/build#L185) uses `node-gyp`, but this is not specified in `packages.json` file and might be missing from the target machine.

**Comment by braydonf** [comment]
`node-gyp` should be installed with `node`, likewise as `npm`.

**Comment by prusnak** [comment]
Maybe, but it's not. Would it hurt to add it to packages.json?

**Comment by braydonf** [comment]
I just did a fresh install of node and node-gyp is included. Perhaps something with the install of node went wrong. 

We are also not using node-gyp directly anymore.
