### ISSUE TITLE
Passing undefined for config object throws weird errors.

### ISSUE THREAD

**Issue by Levino** [bitpay/bitcore-node#410]
We be nice to give a graceful error.

Reproduce:

```js
var index = require('bitcore-node');
var Bitcoin = index.services.Bitcoin;
var Node = index.Node;

var configuration = {
  datadir: '/home/user/.bitcoin',
  network: 'testnet',
  services: [
    {
      name: 'bitcoind',
      module: Bitcoin //,
 //  config: {}
    }
  ]
};

var node = new Node(configuration);

node.start(function() {
  //start the node so the node.on('ready') is actually called. 
});

node.on('ready', function() {
  console.log('Bitcoin Node Ready');
});

node.on('error', function(err) {
  console.error(err);
});

// shutdown the node
node.stop(function() {
  // the shutdown is complete
});

```

Gives: 

```bash
node bitcore.js 

/home/levin/temp/node_modules/bitcore-node/node_modules/bitcore-lib/lib/util/preconditions.js:9
      throw new errors.InvalidState(message);
      ^
Invalid state: undefined
Error
    at Error.NodeError (/home/levin/temp/node_modules/bitcore-node/node_modules/bitcore-lib/lib/errors/index.js:20:41)
    at Object.module.exports.checkState (/home/levin/temp/node_modules/bitcore-node/node_modules/bitcore-lib/lib/util/preconditions.js:9:13)
    at Node._startService (/home/levin/temp/node_modules/bitcore-node/lib/node.js:175:5)
    at /home/levin/temp/node_modules/bitcore-node/lib/node.js:232:12
    at /home/levin/temp/node_modules/bitcore-node/node_modules/async/lib/async.js:181:20
    at iterate (/home/levin/temp/node_modules/bitcore-node/node_modules/async/lib/async.js:262:13)
    at Object.async.forEachOfSeries.async.eachOfSeries (/home/levin/temp/node_modules/bitcore-node/node_modules/async/lib/async.js:281:9)
    at Object.async.forEachSeries.async.eachSeries (/home/levin/temp/node_modules/bitcore-node/node_modules/async/lib/async.js:214:22)
    at Node.start (/home/levin/temp/node_modules/bitcore-node/lib/node.js:229:9)
    at Object.<anonymous> (/home/levin/temp/bitcore.js:18:6)
```

The issue is the out-commented ```config: {}``` above. I expect that an empty object is created when config is undefined.

**Comment by braydonf** [comment]
Relevant precondition: https://github.com/bitpay/bitcore-node/blob/master/lib/node.js#L175

**Comment by braydonf** [comment]
Including a string with message as the second argument for the checkState will give an error message.

**Comment by Levino** [comment]
Why not set config to "{}" when check fails?

**Comment by braydonf** [comment]
Because of the following two preconditions

**Comment by Levino** [comment]
But it works with ```config: {}```!

**Comment by braydonf** [comment]
Yeah, I'm wondering if some code changed and the preconditions didn't get updated. It looks like `node` and `name` are being set.

**Comment by Levino** [comment]
It is testing for them NOT being there, I just saw.

**Comment by Levino** [comment]
I think something like

```js
if (!serviceInfo.config) {
   serviceInfo.config = {}
}
```

should not break anything.

**Comment by braydonf** [comment]
Right, that may be true now. I think the preconditions there may need to be updated to just:
```js
$.checkState(!serviceInfo.name);
```

**Comment by Levino** [comment]
Do you not want a name for the service?

**Comment by Levino** [comment]
These checks look like some checks to prevent usage with "old api" assumptions. Maybe at some point you wanted the name in the config object and then hoisted it up a level later. To be sure that you wouldn't have weird issues when using it with old tests or so someone introduced these checks.

**Comment by braydonf** [comment]
The name is essential to access the API of a service:
```js
self.services[serviceInfo.name] = service;
```

**Comment by Levino** [comment]
But then I would expect
```js
$.checkState(serviceInfo.name);
```

**Comment by braydonf** [comment]
Yes, needs to be updated. Want to submit a PR with the change?

**Comment by Levino** [comment]
Sure can do.

**Comment by braydonf** [comment]
Yeah, I think it's safe to default the config to an object at this point.

**Comment by braydonf** [comment]
The tests with `npm run test` in `/test` should run without configuration. The tests in `./integration` require compiling with `BITCORENODE_ENV=test`.

**Comment by braydonf** [comment]
Just realized that these preconditions are that `config.name` and `config.node` are undefined, since these values are added to the config automatically, and be confusing if overwritten.
