### ISSUE TITLE
Build from source using Bitcoin Classic instead of Bitcoin Core

### ISSUE THREAD

**Issue by chrisrico** [bitpay/bitcore-node#411]
I'm trying to build bitcore-node from source using Bitcoin Classic instead of Bitcoin Core.

What I did is comment out the downloading of binaries in `./bin/install` to force it to build from `./libbitcoind`. Then I cloned Bitcoin Classic into `./libbitcoind`. Patching and building worked perfectly, but when I run the node and call the "getnetworkinfo" JSON-RPC endpoint, it's reporting as `{"version":110200,"subversion":"/Satoshi:0.11.2/" ... }`.

Am I missing something?

**Comment by kleetus** [comment]
I wonder if the patch really did go clean or if something failed before then. The version message should have 'bitcore' appended in the subversion, but this is for P2P version messages and not necessarily the output from getnetworkinfo. But, you are right, the output from getnetworkinfo should look something like this:

{
    "version" : 110200,
    "subversion" : "/Classic:0.11.2/",
    "protocolversion" : 70002,
    "localservices" : "0000000000000001",
    "timeoffset" : -19,
    "connections" : 7,
    "networks" : [
        {
            "name" : "ipv4",
            "limited" : false,
            "reachable" : false,
            "proxy" : "",
            "proxy_randomize_credentials" : false
        },
        {
            "name" : "ipv6",
            "limited" : false,
            "reachable" : false,
            "proxy" : "",
            "proxy_randomize_credentials" : false
        },
        {
            "name" : "onion",
            "limited" : false,
            "reachable" : false,
            "proxy" : "",
            "proxy_randomize_credentials" : false
        }
    ],
    "relayfee" : 0.00005000,
    "localaddresses" : [
    ]
}

**Comment by chrisrico** [comment]
I found the other changes I needed to make:

- `echo v0.11.2.cl1 > PATCH_VERSION` (Bitcoin Classic's release tag)
- Change the GIT URL to Classic's in `./bin/build`

Yet I am still having the same problem. I've attached a log of `npm install`.

[install.txt](https://github.com/bitpay/bitcore-node/files/128820/install.txt)

**Comment by chrisrico** [comment]
Finally fixed my issue. Since `./libbitcoind` already existed, it wasn't checking out the correct tag from the repository.

*facepalm*

It would be really nice if there was an easy way to configure the build to use Bitcoin Classic instead of hard coding the Bitcoin Core repository. I'm not sure the best way to go about that? Environment flag?
