### ISSUE TITLE
Upgrade To 0.12

### ISSUE THREAD

**Issue by praeluceo** [bitpay/bitcore-node#414]
bitcore-node is still running Satoshi:0.11.2(bitcore)

Core 0.12 was released February 23rd: https://github.com/bitcoin/bitcoin/tree/0.12

Please upgrade or provide an upgrade path to Satoshi:0.12.0(bitcore)

Additionally, making the functionality extensible so a node can select which node to run (Core/Classic/etc) would be an interesting approach as well.

**Comment by braydonf** [comment]
+1

**Comment by w4** [comment]
+1

**Comment by braydonf** [comment]
Included in https://github.com/bitpay/bitcore-node/pull/422
