### ISSUE TITLE
How can I change maxconnections?

### ISSUE THREAD

**Issue by elichai** [bitpay/bitcore-node#421]
How can I change the number of maxconnections in the node?
(so that it will connect to e.g. 1000 nodes)

Thanks,
Elichai2.

**Comment by kleetus** [comment]
from: 

https://en.bitcoin.it/wiki/Running_Bitcoin

	-maxconnections=<n>	Maintain at most <n> connections to peers (default: 125)

**Comment by kleetus** [comment]
this is the bitcoin.conf pointed to in ~/.bitcore/bitcore-node.json in "datadir"

**Comment by elichai** [comment]
so that's how I should add it?
```
"datadir": "/root/.bitcore/data",
  "network": "livenet",
  "port": 3001,
  "maxconnections":2500
```

**Comment by braydonf** [comment]
It's a bitcoind option, so in `/root/.bitcore/data/bitcoin.conf`

**Comment by elichai** [comment]
Thanks, but how can I check the number of connected nodes?

**Comment by braydonf** [comment]
If you're using the insight-api the `/status` path gives the number of connections, which is ultimately calling `getInfo`: https://github.com/bitpay/bitcore-node/blob/master/lib/services/bitcoind.js#L344

**Comment by elichai** [comment]
So I should do something like that?
```
var node = new bitcore.Node({***all the Node Data***});
 
var bitcoind = node.services.bitcoind
var info = bitcoind.getInfo();
should.exist(info.connections);
```

**Comment by braydonf** [comment]
Yes, I believe so. You may need to also call `node.start()`, the tests are a good reference point: https://github.com/bitpay/bitcore-node/blob/master/integration/regtest-node.js#L44
