### ISSUE TITLE
getTransactionWithBlockInfo over socket.io omits block info

### ISSUE THREAD

**Issue by jpochyla** [bitpay/bitcore-node#423]
It seems like the underscored fields are somehow omitted from the returned response (and it is therefore identical to `getTransaction`). See here:

https://github.com/bitpay/bitcore-node/blob/master/lib/services/db.js#L420-L422

**Comment by braydonf** [comment]
Thanks for the report!

This should be resolved in latest master, with a new method `getDetailedTransaction` that will serialize correctly.
