### ISSUE TITLE
AddressService.transactionHandler does not report spending transactions 

### ISSUE THREAD

**Issue by jpochyla** [bitpay/bitcore-node#424]
It only iterates the outgoing outputs, not incoming, and so only fills `outputIndexes` field, even though `transactionEventHandler` looks into `inputIndexes` and relays it forward. Seems like a simple enough fix, i'll submit a PR soon. This is needed for proper real-time wallet functionality.

**Comment by jpochyla** [comment]
Mentioned code:

https://github.com/bitpay/bitcore-node/blob/462e4e3cdd15e5d59812e089eb88f6ce8e45066b/lib/services/address/index.js#L234

https://github.com/bitpay/bitcore-node/blob/462e4e3cdd15e5d59812e089eb88f6ce8e45066b/lib/services/address/index.js#L591

**Comment by braydonf** [comment]
The transaction handler now goes through both outputs and inputs (and will work with standard p2sh and p2pkh), see: https://github.com/bitpay/bitcore-node/blob/master/lib/services/bitcoind.js#L558
