### ISSUE TITLE
can't start bitcore-node from build

### ISSUE THREAD

**Issue by z3ustb** [bitpay/bitcore-node#426]
Following the steps from this link https://github.com/bitpay/bitcore-node/blob/master/docs/build.md, the last step was failed and here is the output:

root@ubuntu:~/bitcore-node# npm start

> bitcore-node@2.1.0-dev start /root/bitcore-node

> node bin/start.js

module.js:338

    throw err;

          ^

Error: Cannot find module 'bitcoind/package.json'

    at Function.Module._resolveFilename (module.js:336:15)

    at Function.Module._load (module.js:278:25)

    at Module.require (module.js:365:17)

    at require (module.js:384:17)

    at Function.setupServices (/root/bitcore-node/lib/scaffold/start.js:51:30)

    at start (/root/bitcore-node/lib/scaffold/start.js:203:31)

    at Object.<anonymous> (/root/bitcore-node/bin/start.js:8:1)

    at Module._compile (module.js:460:26)

    at Object.Module._extensions..js (module.js:478:10)

    at Module.load (module.js:355:32)

npm ERR! Linux 3.19.0-25-generic

npm ERR! argv "/root/.nvm/versions/node/v0.12.12/bin/node" "/root/.nvm/versions/node/v0.12.12/bin/npm" "start"

npm ERR! node v0.12.12

npm ERR! npm  v2.14.9

npm ERR! code ELIFECYCLE

npm ERR! bitcore-node@2.1.0-dev start: `node bin/start.js`

npm ERR! Exit status 1

And the `build/Release/bitcoind.node` wasn't found

**Comment by braydonf** [comment]
If `build/Release/bitcoind.node` isn't found there is likely another error that happened earlier with `npm install`  but may have been missed.

**Comment by z3ustb** [comment]
I haven't found any errors but only some warning. Here is the output of npm install
--------------------
[root@ubuntu ~bitcore-node]# npm install
npm WARN deprecated graceful-fs@3.0.8: graceful-fs version 3 and before will fail on newer node releases. Please update to graceful-fs@^4.0.0 as soon as possible.
\
> leveldown@1.4.4 install /root/bitcore-node/node_modules/leveldown
> prebuild --install


> utf-8-validate@1.2.1 install /root/bitcore-node/node_modules/socket.io-client/node_modules/engine.io-client/node_modules/ws/node_modules/utf-8-validate
> prebuild --download

prebuild WARN install /root/bitcore-node/node_modules/socket.io-client/node_modules/engine.io-client/node_modules/ws/node_modules/utf-8-validate/build/Debug/validation.node: ELF load command past end of file
make: 进入目录“/root/bitcore-node/node_modules/socket.io-client/node_modules/engine.io-client/node_modules/ws/node_modules/utf-8-validate/build”
  CXX(target) Release/obj.target/validation/src/validation.o
  SOLINK_MODULE(target) Release/obj.target/validation.node
  COPY Release/validation.node
make: 离开目录“/root/bitcore-node/node_modules/socket.io-client/node_modules/engine.io-client/node_modules/ws/node_modules/utf-8-validate/build”

> utf-8-validate@1.2.1 install /root/bitcore-node/node_modules/socket.io/node_modules/engine.io/node_modules/ws/node_modules/utf-8-validate
> prebuild --download

prebuild WARN install /root/bitcore-node/node_modules/socket.io/node_modules/engine.io/node_modules/ws/node_modules/utf-8-validate/build/Debug/validation.node: ELF load command past end of file
make: 进入目录“/root/bitcore-node/node_modules/socket.io/node_modules/engine.io/node_modules/ws/node_modules/utf-8-validate/build”
  CXX(target) Release/obj.target/validation/src/validation.o
  SOLINK_MODULE(target) Release/obj.target/validation.node
  COPY Release/validation.node
make: 离开目录“/root/bitcore-node/node_modules/socket.io/node_modules/engine.io/node_modules/ws/node_modules/utf-8-validate/build”

> utf-8-validate@1.2.1 install /root/bitcore-node/node_modules/socket.io/node_modules/socket.io-client/node_modules/engine.io-client/node_modules/ws/node_modules/utf-8-validate
> prebuild --download

prebuild WARN install /root/bitcore-node/node_modules/socket.io/node_modules/socket.io-client/node_modules/engine.io-client/node_modules/ws/node_modules/utf-8-validate/build/Debug/validation.node: ELF load command past end of file
make: 进入目录“/root/bitcore-node/node_modules/socket.io/node_modules/socket.io-client/node_modules/engine.io-client/node_modules/ws/node_modules/utf-8-validate/build”
  CXX(target) Release/obj.target/validation/src/validation.o
  SOLINK_MODULE(target) Release/obj.target/validation.node
  COPY Release/validation.node
make: 离开目录“/root/bitcore-node/node_modules/socket.io/node_modules/socket.io-client/node_modules/engine.io-client/node_modules/ws/node_modules/utf-8-validate/build”

> bufferutil@1.2.1 install /root/bitcore-node/node_modules/socket.io/node_modules/engine.io/node_modules/ws/node_modules/bufferutil
> prebuild --download


> bufferutil@1.2.1 install /root/bitcore-node/node_modules/socket.io/node_modules/socket.io-client/node_modules/engine.io-client/node_modules/ws/node_modules/bufferutil
> prebuild --download


> bufferutil@1.2.1 install /root/bitcore-node/node_modules/socket.io-client/node_modules/engine.io-client/node_modules/ws/node_modules/bufferutil
> prebuild --download

npm WARN cannot run in wd bitcore-node@2.1.0-dev ./bin/install (wd=/root/bitcore-node)
leveldown@1.4.4 node_modules/leveldown
├── fast-future@1.0.1
├── abstract-leveldown@2.4.1 (xtend@4.0.1)
└── prebuild@2.9.2 (os-homedir@1.0.1, expand-template@1.0.2, noop-logger@0.1.1, xtend@4.0.1, github-from-package@0.0.0, tar-fs@1.12.0, minimist@1.2.0, mkdirp@0.5.1, rc@1.1.6, pump@1.0.1, simple-get@1.4.3, tar-stream@1.5.1, npmlog@2.0.3, ghreleases@1.0.4, node-gyp@3.3.1)

socket.io@1.3.7 node_modules/socket.io
├── debug@2.1.3 (ms@0.7.0)
├── has-binary@0.1.6 (isarray@0.0.1)
├── socket.io-parser@2.2.4 (isarray@0.0.1, debug@0.7.4, component-emitter@1.1.2, json3@3.2.6)
├── socket.io-adapter@0.4.0 (debug@2.2.0, socket.io-parser@2.2.2)
├── engine.io@1.5.4 (base64id@0.1.0, engine.io-parser@1.2.2, accepts@1.1.4, ws@0.8.0)
└── socket.io-client@1.3.7 (to-array@0.1.3, component-emitter@1.2.0, indexof@0.0.1, component-bind@1.0.0, backo2@1.0.2, object-component@0.0.3, parseuri@0.0.2, engine.io-client@1.5.4)

socket.io-client@1.3.7 node_modules/socket.io-client
├── to-array@0.1.3
├── component-emitter@1.2.0
├── indexof@0.0.1
├── component-bind@1.0.0
├── object-component@0.0.3
├── backo2@1.0.2
├── has-binary@0.1.6 (isarray@0.0.1)
├── debug@2.1.3 (ms@0.7.0)
├── socket.io-parser@2.2.4 (isarray@0.0.1, debug@0.7.4, component-emitter@1.1.2, json3@3.2.6)
├── parseuri@0.0.2 (better-assert@1.0.2)
└── engine.io-client@1.5.4 (component-emitter@1.1.2, component-inherit@0.0.3, has-cors@1.1.0, xmlhttprequest-ssl@1.5.1, parseqs@0.0.2, parsejson@0.0.1, parseuri@0.0.4, engine.io-parser@1.2.2, ws@0.8.0)

**Comment by braydonf** [comment]
Doesn't look like the install script is running:
```
npm WARN cannot run in wd bitcore-node@2.1.0-dev ./bin/install (wd=/root/bitcore-node)
```

**Comment by braydonf** [comment]
This looks related: https://github.com/npm/npm/issues/3497

**Comment by braydonf** [comment]
I would try running as a user instead of the root.

**Comment by braydonf** [comment]
Let us know if there are any other issues, this looks to be resolved by installing without root privileges, as similar to https://github.com/bitpay/bitcore-node/issues/362#issuecomment-209731431:

**Reference Docs**:
- https://docs.npmjs.com/misc/config#user 
- https://docs.npmjs.com/misc/scripts#user

**Solutions when using `npm`**:
- Use the `--unsafe-perm` flag
- Run `npm install` without root privileges
- Configure npm user that has the correct privileges

**Comment by z3ustb** [comment]
OK. It works now. Thanks!
