### ISSUE TITLE
How to share data directory with Bitcoin Core?

### ISSUE THREAD

**Issue by pinheadmz** [bitpay/bitcore-node#428]
Can a Bitcore node use the same blockchain data as a Bitcoin Core node running on the same system? Where can I direct Bitcore-node to a custom data directory?

**Comment by braydonf** [comment]
The "datadir" config in `bitcore-node.json`: https://bitcore.io/guides/full-node#configure-the-network

**Comment by gabegattis** [comment]
Just be aware that you cannot have 2 nodes running with the same datadir at the same time.

**Comment by dexter369** [comment]
not able to access https://bitcore.io/guides/full-node#configure-the-network can you please specify where the datadir config needs to be setup as there is only bitcore.config.json
