### ISSUE TITLE
Need help

### ISSUE THREAD

**Issue by Bitcoinsis** [bitpay/bitcore-node#430]
I am coding a new bitoin wallet and as i am newbie to bitcoin coding i need help with installation or bitcoin server.

There are 3 types bitcore, bitcore-node and bitcoin-daemon.

which one is used to create your own bitcoin wallet server to create API and all other stuff to be used with my website?

I am confused because i don't know the difference between those so if there is anyone can help me with choosing the right thing for my purpose that will be very help full.

I need to install bitcoin server to attach with my website so users can generate wallet addresses and can make transactions.

**Comment by gabegattis** [comment]
https://bitcore.io/guides/wallet-service is probably what you are looking for. This guide shows you how to setup bitcore with bitcore-wallet-service (BWS). BWS is the server backend for Copay and bitcore-wallet-client.

[BWS](https://github.com/bitpay/bitcore-wallet-service) handles creating wallets, generating addresses, creating unsigned transactions and transaction proposals, etc. BWS does not handle private keys or signing transactions.

**Comment by braydonf** [comment]
There is also https://forum.bitcore.io/ for support and help from the community.
