### ISSUE TITLE
How to check if an output is unspent

### ISSUE THREAD

**Issue by elichai** [bitpay/bitcore-node#431]
Hi,
I tried a couple of hours to figure out how to check if a specific output is unspent (if it's an input inside any confirmed transacion) with no luck.

Is it even possible?

Thanks,
Elichai2.

**Comment by braydonf** [comment]
Yes, `getDetailedTransaction` will include spent information for each output. There is also `getAddressUnspentOutputs`.

Please see: https://github.com/bitpay/bitcore-node/blob/master/docs/services/bitcoind.md
