### ISSUE TITLE
blocknotify option

### ISSUE THREAD

**Issue by elichai** [bitpay/bitcore-node#433]
Hi,
Is there any feature like blocknotify in bitcore-core?
(I want to call a function wherever a new block arrive)

Thanks,
elichai2

**Comment by kleetus** [comment]
https://github.com/bitpay/bitcore-node/blob/766d87192a2570d635442e8fdd32b3b579669b05/lib/services/address/index.js#L449

**Comment by braydonf** [comment]
Also landing soon, there are several events for block via websocket and from an EventEmitter:
https://github.com/braydonf/bitcore-node/blob/aa7f0d7c605212eb8415e1de10721df43ae179c0/docs/services/bitcoind.md#events

Also bitcoind is used if you would like to use blocknotify in your `bitcoin.conf`.

**Comment by elichai** [comment]
@braydonf is the an ETA for this patch to enter the main code?

**Comment by braydonf** [comment]
It's landed on master, and available on bitcore@4.0.0 and bitcore-node@3.0.0
