### ISSUE TITLE
Question: how to install Bitcore on top of existing running full node, for Trezor

### ISSUE THREAD

**Issue by pinheadmz** [bitpay/bitcore-node#435]
Now that MyTrezor.com supports Bitcore, I would like to install Bitcore on top of my existing full node. Is there documentation on installing Bitcore as a service on top of bitcoind? Obviously I do not need networking, P2P or a second copy of the blockchain from Bitcore, just want to connect my existing node for use with MyTrezor.

Ideally this is possible without changes to Bitcoin Core (or switching to the BitPay client) as I would also like to apply Bitcore to my Bitcoin Unlimited node.

**Comment by braydonf** [comment]
Bitcore runs a modified version of bitcoind with additional indexes (see: https://github.com/bitpay/bitcoin/tree/0.12-bitcore and https://bitcore.io/bitcoin), it's necessary to run that.

**Comment by braydonf** [comment]
Also the forum at https://forum.bitcore.io/ may be better suited for questions and general discussion.

**Comment by pinheadmz** [comment]
thanks!
