### ISSUE TITLE
"npm install -g bitcore" fails

### ISSUE THREAD

**Issue by emcor01** [bitpay/bitcore-node#444]
I cannot preinstall bitcore, after the command "npm install -g bitcore" I get the below error message (and attached log).

The command "npm" gives the correct "help" section though.

Can someone explain how to fix this issue?

npm : '.' is not recognized as an internal or external command,
At line:1 char:1
+ npm install -g bitcore
+ ~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: ('.' is not reco...ternal command,:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
 
operable program or batch file.

npm
 
ERR!
 Windows_NT 10.0.10586

npm
 
ERR!
 
argv
 "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "bitcore"

npm
 ERR!
 
node v4.4.5

npm
 ERR!
 
npm 
 v2.15.5

npm
 
ERR!
 code
 ELIFECYCLE

npm
 ERR!
 bitcore-node@3.0.0 preinstall: `./scripts/download`

npm
 
ERR!
 Exit status 1

npm
 ERR!
 

npm
 
ERR!
 Failed at the bitcore-node@3.0.0 preinstall script './scripts/download'.

npm
 
ERR!
 This is most likely a problem with the bitcore-node package,

npm
 
ERR!
 not with npm itself.

npm
 
ERR!
 Tell the author that this fails on your system:

npm
 
ERR!
     ./scripts/download

npm
 
ERR!
 You can get information on how to open an issue for this project with:

npm
 
ERR!
     npm bugs bitcore-node

npm
 
ERR!
 Or if that isn't available, you can get their info via:

npm
 
ERR!
 

npm
 
ERR!
     npm owner ls bitcore-node

npm
 
ERR!
 There is likely additional logging output above.

npm
 ERR!
 Please include the following file with any support request:

npm
 
ERR!
     C:\Users\user\npm-debug.log
[npm-debug.pdf](https://github.com/bitpay/bitcore-node/files/299388/npm-debug.pdf)

**Comment by braydonf** [comment]
Please see the prerequisites at https://github.com/bitpay/bitcore-node#prerequisites and issue https://github.com/bitpay/bitcore-node/issues/271
