### ISSUE TITLE
Restarting service without restarting node?

### ISSUE THREAD

**Issue by igorvlassov** [bitpay/bitcore-node#445]
Hello,
I try to develop service for Bitcore and every time I make some changes I restarts the node to reload my service and check changes. Sometimes this requires significant enough amount of time.
Is it possible to restart it without full node restart?
Thanks in advance,
Igor

**Comment by braydonf** [comment]
No. Though restarting with testnet is faster. You can also decrease `-checkblocks` while developing.

**Comment by igorvlassov** [comment]
OK, @braydonf Thanks.
