### ISSUE TITLE
Installation problems

### ISSUE THREAD

**Issue by igorvlassov** [bitpay/bitcore-node#447]
Dear Sirs,
Just trying to install bitcore into home folder with command
`npm install bitcore`
 on Linux server with node -v = v6.2.1
npm -v=3.9.3, g++ --version=4.8.2 20140120 (Red Hat 4.8.2-15)
Get error: 
```
> bufferutil@1.2.1 install /home/develop/bitcore/node_modules/bufferutil
> node-gyp rebuild

make: Entering directory `/home/develop/bitcore/node_modules/bufferutil/build'
  CXX(target) Release/obj.target/bufferutil/src/bufferutil.o
In file included from ../src/bufferutil.cc:16:
../../nan/nan.h:43:3: error: #error This version of node/NAN/v8 requires a C++11 compiler
In file included from ../src/bufferutil.cc:7:
```
and other multiple errors.
Any ideas how to fix this?

Thanks in advance,
Igor

**Comment by braydonf** [comment]
You need to have a C++11 compiler with your distro. Our travis build had the same issue and resolved with: https://github.com/bitpay/bitcore-node/blob/master/.travis.yml#L3-11 *(not sure about other distros)*.

https://forum.bitcore.io/ is available for support and general questions/discussion.

**Comment by igorvlassov** [comment]
The problem is with npm
 https://github.com/npm/npm/issues/12318
Seems solved partially by downgrading.
