### ISSUE TITLE
No height variable inside Transaction

### ISSUE THREAD

**Issue by elichai** [bitpay/bitcore-node#470]
Hi,
I want to calculate the number of confirmation of a Transaction and I saw this line:
`var confirmations = node.services.bitcoind.height - transaction.height + 1;`
So I used this to get the Transaction object: https://github.com/bitpay/bitcore-node/blob/master/lib/services/bitcoind.js#L1832

But I get always Undefined Error for the transaction.height.

Thanks,
Elichai.

**Comment by braydonf** [comment]
`getDetailedTransaction` has the height
