### ISSUE TITLE
 Connection to bitcoind failed

### ISSUE THREAD

**Issue by drrest** [bitpay/bitcore-node#48]
Tip is 000000000019d6689c085ae165831e934ff763ae46a2a6c172b3f1b60a8ce26f
Connection to bitcoind failed
network monitor disconnected

Error: connect ECONNREFUSED
    at errnoException (net.js:901:11)
    at Object.afterConnect [as oncomplete] (net.js:892:19)

bitcoind works perfect

**Comment by maraoz** [comment]
is your config ok? check config/default.yml
