### ISSUE TITLE
Any option in bitcore-node.json not to sync the blockchain? 

### ISSUE THREAD

**Issue by vdidonato** [bitpay/bitcore-node#483]
Is there any option in bitcore-node.json I can use to run the bitcore-node without syncing the blockchain? My use case is that I need the data and I get it through insight-api. Now, I realized that while bitcore-node syncs the blockchain, insight-api is slower in serving the calls (~0.5 ms vs ~100 ms)...so I would like to have a mode in which it only replies to my queries instead of keeping syncing.

**Comment by braydonf** [comment]
Not sure that I understand the motivation, but you can max sure that bitcoind isn't connect to any peers to receive new blocks. I've done this for debugging purposes by editing the bitcoin.conf and setting maxconnections to 0.

**Comment by vdidonato** [comment]
This is great! I tried it and it works. 
The motivation is that I'm doing research on the blockchain and I'm not interested in having always fresh data. What I want is a system that replies to my queries (through insight-api) as quickly as possible and I noticed that while the node is syncing it takes more time to give me the data.

**Comment by braydonf** [comment]
In that case you may also want to take a look at modifying/increasing these settings, if you haven't already:
- dbcache
- rpcthreads
- rpcworkqueue

**Comment by vdidonato** [comment]
I did modify dbcache and rpcthreads but I didn't know about rpcworkqueue. Is it documented anywhere? Thanks a lot!

**Comment by braydonf** [comment]
I don't think it's documented that well, but here is the line in the source code: https://github.com/bitpay/bitcoin/blob/3522f49f5ae74fe3ef310fad6fa7e09d65c9c1b8/src/httpserver.cpp#L436
