### ISSUE TITLE
Mempool never queried with start/end with getAddressHistory

### ISSUE THREAD

**Issue by runn1ng** [bitpay/bitcore-node#484]
When you query server with getAddressHistory and start/end parameters, mempool is never queried 

See
https://github.com/bitpay/bitcore-node/blob/7b0f2548798f56d48f4f80a5cd92408978ddf160/lib/services/bitcoind.js#L1220-L1222

````javascript
Bitcoin.prototype.getAddressTxids = function(addressArg, options, callback) {
...
  if (rangeQuery) {
    queryMempool = false;
  }
````

It makes sort of sense, since the mempool transactions won't be in start/end range. But there is currently no way to say to bitcore "give me the history, starting from block X, up to now, including unconfirmed transactions".

Why do we need this. We cache transactions on the client, so we only ask for all the new transactions from a given point onwards (so the index on server is not used when it's not needed). The user then doesn't see the unconfirmed transactions.

It would make sense to either always query mempool when the caller explicitly asks for that, *or* - perhaps better - to add a possibility to ask for txIds *only from mempool*.

**Comment by braydonf** [comment]
You may be interested in some of the lower level functionality of bitcoind RPC that has a `getaddressmempool` that returns information only from the mempool, and how the results from bitcore-node methods include items from the mempool. More information is at: https://bitcore.io/guides/bitcoin#new-rpc-methods-and-updates

**Comment by runn1ng** [comment]
Yep, that method is great, but it cannot be called from socket.io connection, AFAIK. 

If it's OK with you, I will add some call to lib/services/bitcoind.js in this repo, which will make it accessible directly. (It's already called as a part of different calls anyway.)
