### ISSUE TITLE
split into different projects

### ISSUE THREAD

**Issue by maraoz** [bitpay/bitcore-node#54]

**Comment by carnesen** [comment]
What do you have in mind for the split project architecture?

**Comment by maraoz** [comment]
We want to move the api/ folder to a new project called bitcore-node-http.
The idea is to separate the network and database handling code from the
webapp code (which uses express). What do you think of this?

**Comment by carnesen** [comment]
ACK, as they say.

**Comment by kentdome** [comment]
Sounds good.

**Comment by yangit** [comment]
I see that bitcore-node-http is not yet present while HTTP API endpoints have been taken away from bitcore-node. Am I missing something? Any way I can get HTTP api with bitcore-node now?

**Comment by braydonf** [comment]
Using insight-api as a Bitcore Node service is currently the way to include HTTP API endpoints, currently in development at: https://github.com/bitpay/insight-api/tree/v0.3.0. Additional HTTP API endpoints can be added with other services.
