### ISSUE TITLE
Enabling Bitcoin Cash in bitcore-node.json? 

### ISSUE THREAD

**Issue by rickygu** [bitpay/bitcore-node#540]
I'm running my own BWS for the copay app. Is there any documentation on how to enable Bitcoin Cash on a bitcore node? This is my config right now working well for livenet/testnet connected to copay:
```javascript
{
  "network": "livenet",
  "port": 3001,
  "services": [
    "bitcoind",
    "bitcore-wallet-service",
    "insight-api",
    "web"
  ],
  "https": true,
  "httpsOptions": {
    "key": "/home/bws/livenet/key.nopass.pem",
    "cert": "/home/bws/livenet/cert.pem"
  },
  "servicesConfig": {
    "bitcore-wallet-service": {
      "bwsPort": 443
    },
    "bitcoind": {
      "spawn": {
        "datadir": "/home/bws/.bitcoin",
        "exec": "/home/bws/livenet/node_modules/bitcore-node/bin/bitcoind"
      }
    }
  }
}  
```

**Comment by Daniel600** [comment]
Hi Ricky - where you able to get Bitcore to work with bitcoin cash if so how?

**Comment by Plorark** [comment]
Joining the question. Maybe the answer to this also teaches us how to connect to other altcoins

**Comment by shamoons** [comment]
Does this work? It seems that this is still running `bitcoind`?
