### ISSUE TITLE
AssertionError [ERR_ASSERTION]: Timestamp is required when saving a transaction.

### ISSUE THREAD

**Issue by cronos-polis** [bitpay/bitcore-node#558]
Hello, Working with a Port of Bitcore-Node to another blockchain.
Seems you made it easier now. 
But I can't start syncing blocks from peer using bitcore-p2p. Can I get more reference on this error:

```
AssertionError [ERR_ASSERTION]: Timestamp is required when saving a transaction.
```

**Comment by osagga** [comment]
How did you manage to fix this problem? I'm running into it right now

**Comment by pshenmic** [comment]
The problem is that block timestamp extracted in the event (timstamp service, onBlock event) is undefined (block.ts), then undefined saved in the cache which result (obviously) in false assertion. The incoming block I suppose is bcoin block, so it should be block.time instead.
