### ISSUE TITLE
Node 8 doesn't show transactions in mempool (unconfirmed) 

### ISSUE THREAD

**Issue by osagga** [bitpay/bitcore-node#576]
I have noticed that bitcore-node v8 doesn't show the unconfirmed transactions (in mempool), is there a specific reason to why it does that? The previous versions of Bitcore node process and show the unconfirmed transactions in addition to the number of confirmations.

**Comment by micahriggan** [comment]
Hello @osagga, all development is occuring on the repo @ https://github.com/bitpay/bitcore/tree/v8.0.0

I believe the mempool transactions should be available, if not just let me know

**Comment by osagga** [comment]
Yes this is fixed in the other repo, thanks!
