### ISSUE TITLE
IDEA: Implement MongoDB for storage.

### ISSUE THREAD

**Issue by adrianromanko** [bitpay/bitcore-node#65]
Replace leveldb.

**Comment by ysangkok** [comment]
Why?

**Comment by pnagurny** [comment]
Leveldb is much faster for indexing blockchain data. We actually originally used leveldb when writing the original Insight API. It was very slow. We switched to using leveldb.

In Bitcore Node we are using leveldb for indexing blockchain data. However, services are free to use other databases for storing other data.

**Comment by ysangkok** [comment]
> We actually originally used **leveldb** when writing the original Insight API. It was very slow. We switched to using **leveldb**.

This makes no sense. You switched to the thing you were already using?
