### ISSUE TITLE
Error:  { [Error: write EPIPE] code: 'EPIPE', errno: 'EPIPE', syscall: 'write' }

### ISSUE THREAD

**Issue by kentdome** [bitpay/bitcore-node#72]
000000000000040922c830bae82aac73edfc670b65016f87f852181e909ad1fc 212784 vel 0 b/s 60.0093066542578% synced
Error:  { [Error: write EPIPE] code: 'EPIPE', errno: 'EPIPE', syscall: 'write' }
network monitor disconnected

/bitcore-node/lib/networkmonitor.js:110
    throw reason;
          ^
Error: write EPIPE
    at errnoException (net.js:901:11)
    at Object.afterWrite (net.js:718:19)
npm ERR! weird error 8
npm WARN This failure might be due to the use of legacy binary "node"
npm WARN For further explanations, please read
/usr/share/doc/nodejs/README.Debian

Restarting the server, bitcoind, and running  npm start again yields:

restarting Tip is 000000000000040922c830bae82aac73edfc670b65016f87f852181e909ad1fc
No blockchain yet
No blockchain yet
No blockchain yet
...
All headers fetched, total = 212785
...

--just appears to sit there. Any logs we can check?

**Comment by maraoz** [comment]
@kentdome Thanks for reporting! Is it possible that you've ran out of disk space? (I don't think so, but just to be sure)

I'll dig into this. Got this error myself while developing a while back, will try to reproduce

**Comment by kentdome** [comment]
Thanks for looking into it. No, got 83GB free and looks like bitcore-node synchronized up ~22GB worth.

    Filesystem      Size  Used Avail Use% Mounted on
    /dev/sdb1       110G   22G   83G  21% /bitcore
    root@dev1:/bitcore# du -ch | grep total
    22G	total

I was unable to get it to continue it's sync process :( so I've removed all and trying to resync it again using the latest bitcoind 0.10 version.

**Comment by maraoz** [comment]
Sorry to hear that :( 
Hopefully we can find and fix the bug to prevent this happening in the future!

**Comment by kentdome** [comment]
60% and still ticking. My initial test was on an SSD but following the above crash/error I opted to try on a larger platter drive (just in case)-- definitely starting to slow down.

00000000000003936fde80ae037e59483af2a96ad62e8fb653fbc357d3957c98 213384 vel 0.2 b/s 60.13137464317215% synced

GET /v1/node 200 4.277 ms - 116

{
  "sync": 0.6013137464317215,
  "peerCount": 1,
  "version": "0.1.0",
  "network": "livenet",
  "height": 213384
}

**Comment by kentdome** [comment]
Unfortunately it crashed again:

00000000000004db9b4dfa28fe6d5af99e88f7f2b94ea91c7d6181e6cf7f5433 215954 vel 0.2 b/s 60.85559779407828% synced
FATAL ERROR: CALL_AND_RETRY_2 Allocation failed - process out of memory
Aborted (core dumped)
npm ERR! weird error 134
npm WARN This failure might be due to the use of legacy binary "node"
npm WARN For further explanations, please read
/usr/share/doc/nodejs/README.Debian

npm ERR! not ok code 0

**Comment by ShaliDaliHaliDa** [comment]
Same issue. It got stuck at around 59% so I upgraded to the latest bitcoin core (0.10.1) and tried again.

No blockchain yet
No blockchain yet
No blockchain yet
No blockchain yet
No blockchain yet
No blockchain yet
All headers fetched, total = 212372

Appears to be stuck.

**Comment by ShaliDaliHaliDa** [comment]
Same error. Crashes with: Unhandled rejection TypeError: Cannot read property 'length' of undefined

**Comment by braydonf** [comment]
Also ran into the 'process out of memory' error also, at around 50% sync.

**Comment by kentdome** [comment]
Any updates? Any luck?

**Comment by OSSDeveloper** [comment]
"No blockchain yet" 

bitcore-node is single threaded & sync is a processor heavy operation. It takes some time once you stop the operation and restart it for sync to start again(hours in case of slow processor). 

@maraoz -  Solution might be to use node cluster for sync, utilizing all the processors available.

**Comment by braydonf** [comment]
Don't think this is relevant anymore. 

And syncing performance should be much improved in the master branch currently.
