### ISSUE TITLE
All responses are missing hash/id fields

### ISSUE THREAD

**Issue by thesoftwarejedi** [bitpay/bitcore-node#74]
Querying for a list of blocks, or a list of transactions in a block does not provide the ids, or hashes, of the entities returned.  Maybe I'm missing something, but this makes it awfully difficult to be usable...

/v1/blocks returns the following, which contains no block hashes, or txids:

    [
      {
        "header": {
          "version": 1,
          "prevHash": "0000000000000000000000000000000000000000000000000000000000000000",
          "merkleRoot": "4a5e1e4baab89f3a32518a88c31bc87f618f76673e2cc77ab2127b7afdeda33b",
          "time": 1231006505,
          "bits": 486604799,
          "nonce": 2083236893
        },
        "transactions": [
          {
            "version": 1,
            "inputs": [
              {
                "prevTxId": "0000000000000000000000000000000000000000000000000000000000000000",
                "outputIndex": 4294967295,
                "sequenceNumber": 4294967295,
                "script": "04ffff001d0104455468652054696d65732030332f4a616e2f32303039204368616e63656c6c6f72206f6e206272696e6b206f66207365636f6e64206261696c6f757420666f722062616e6b73"
              }
            ],
            "outputs": [
              {
                "satoshis": 5000000000,
                "script": "4104678afdb0fe5548271967f1a67130b7105cd6a828e03909a67962e0ea1f61deb649f6bc3f4cef38c4f35504e51ec112de5c384df7ba0b8d578a4c702b6bf11d5fac"
              }
            ],
            "nLockTime": 0
          }
        ]

**Comment by braydonf** [comment]
This looks like the output from `block.toObject()`, which doesn't include the hash (since it's a computed property). We may either want to add the hash to the `toObject()` result, or have the API responses for v1 include a custom JSON format.

**Comment by thesoftwarejedi** [comment]
Transaction doesn't either, and it sure would be nice to have the addresses base58enc there in the txs too.

Whats the release schedule look like on this project - I was hoping to use it for developing a personal project.  Should I look into insight-api instead?  I hesitate to do that because it won't support my latest node version according to the docs (out of order blocks).

Alternatively, I can enhance this myself with these missing pieces...  What about the events API - is that fully functional?  Any project status page would be helpful.

**Comment by kentdome** [comment]
Sorry for an off-topic question but how were you able to sync the blockchain? What version of bitcore are you using? Thanks.

**Comment by thesoftwarejedi** [comment]
npm install
    npm start

I'm sure I got a slew of errors or such on the install that I had to google and install dependencies or tweak the command line. I can't recall specifics. If you're having an issue, maybe post the issue and we can help.

**Comment by kentdome** [comment]
Unfortunately that didn't work for me. The initial sync runs to about 60% and crashes every time https://github.com/bitpay/bitcore-node/issues/73

I've tried on three different computers, i7, SSD, 36GB memory etc. I tried with bitcoin core 0.10.0 and 0.10.1 and the older 0.9 version. Any suggestions?

**Comment by thesoftwarejedi** [comment]
Oh, it hasn't completed yet. Ha. Probably won't. It's taking forever.  I've started investigating insight instead

**Comment by kentdome** [comment]
I was under the impression that Bitcore-node is the new / eventual replacement for Insight. How many % did yours sync?

**Comment by thesoftwarejedi** [comment]
I'm moving the heavy lifting onto another machine right now.  It got to about 36% on my raspberry pi and an old desktop.  Throwing it on an i7 now to see if I can get it to go 100%, then I'll look into the code to tweak it to my liking.  Alternatively, I may just go with insight since it's good out of the box.  @braydonf - any timeframe details available for this replacing insight-api?

**Comment by carnesen** [comment]
I don't know the internal timeline for this, but I wouldn't hold my breath.
The two main contributors to this project are no longer employed at BitPay,
and there's indication that the intent is to turn bitcore-node into its own
full node of sorts, which is IMO significantly more difficult than an
insight-api-like web service layer on top of bitcoind. See
https://github.com/bitpay/bitcore-node/issues/57, for example.

**Comment by thesoftwarejedi** [comment]
Thanks @carnesen.  Yeah, a wrapper for bitcoind's library, not a true full node in js.  Definitely sounds like someone's baby that they're probably not going to finish now.  Thanks.

@kentdome mine got stuck at:
    0000000000000948161fcdb06d515c124a9d8589afa57f138f8be9f8d0d8b8ea 128296 vel 0 b/s 35.75557252504083% synced
However, after a restart it's continuing on past that spot.  I'm going to try and get it to 100%, then see if I can tweak the code to have the right fields, then do some benchmarks for this vs Insight.

**Comment by braydonf** [comment]
Hey, sorry for getting off-topic to this issue. But yes, as @carnesen has mentioned, there is intention to run Bitcoin Core code in a Node.js process, and we're currently working on making progress in that area.

**Comment by thesoftwarejedi** [comment]
Thanks, to refocus this actual issue for anyone scrolling down:

Objects are missing ids/hashes 

Previously diagnosed: 
> This looks like the output from block.toObject(), which doesn't include the hash (since it's a computed property). We may either want to add the hash to the toObject() result, or have the API responses for v1 include a custom JSON format.

I may try and tackle this if my instance ever completely syncs.  The speed in which it initial syncs is very concerning.

**Comment by kentdome** [comment]
Any luck with the sync?

**Comment by braydonf** [comment]
Please take a look at [chainlib-bitcoin](https://github.com/bitpay/chainlib-bitcoin), which we can [integrate with bitcore-node](https://github.com/bitpay/bitcore-node/issues/76), the sync should be working.

**Comment by thesoftwarejedi** [comment]
@kentdome I did not ever get it to sync, and instead switched to using insight-api with RPC syncing.

**Comment by braydonf** [comment]
Spawned an issue at Bitcore: https://github.com/bitpay/bitcore/issues/1308

**Comment by braydonf** [comment]
Fixed in: https://github.com/bitpay/bitcore/pull/1311
