### ISSUE TITLE
output_summary instead of output_full

### ISSUE THREAD

**Issue by vdidonato** [bitpay/bitcore-node#78]
This doc (https://docs.google.com/document/d/1rXQdfr8VDBSzheEn0KynnCKCMB0oAsMunkjdG4aY-18/edit#) says that the endpoint:

/v1/transaction/:hash/outputs/:index

should return an output_full with attached:

transaction_id
index
satoshis
script
spent
spending_transactions
type: ‘p2sh’, ‘p2pkh’, etc.

Unfortunately I only see 
satoshis
script

namely an output_summary.

Is it because I'm not fully synchronized? I don't think this is the issue because I'm asking for the outputs of a really old transaction and I'm halfway the full synchronization.

Thanks

**Comment by braydonf** [comment]
This may be more related to insight-api.
