### ISSUE TITLE
Feature-request: Limit amount of cached data.

### ISSUE THREAD

**Issue by pakar** [bitpay/bitcore-node#83]
Hello,

I'm running bitcore-node on a quite small system and have noticed that it tends to grow quite a bit. My current workaround (after the latest cached headers addition) is to restart the process from time to time..

At start right now it goes to ~16% of system memory, and after 20 minutes or so it has grown to 20-22% of total system memory. I think this is a result of caching quite a bit of data, and i think it would be a good thing to clean the cache from time to time.
Performance-wise i cannot really see any difference in blocks/s before and after the restart so i think this would be safe.

**Comment by pakar** [comment]
node-memwatch trace:

Probing RPC connection to check health...
Listening on port 8081
Fetching hashes from db...
183001 headers cached
Tip is 0000000000000844473d11e706c94e4dab9190601d2bc9a6ec9fb41118217abe
1 non-cached headers loaded
starting network monitor
No blocks yet
000000000000088d29b62adce8a47172af35bbac213092cd4d8c5c6eb8eb2309 183002 vel 36600.4 b/s 50.17657574660832% synced
HEAP_DIFF
{ before: 
   { nodes: 57584,
     time: Fri Jul 10 2015 17:49:38 GMT+0200 (CEST),
     size_bytes: 8620496,
     size: '8.22 mb' },
  after: 
   { nodes: 942463,
     time: Fri Jul 10 2015 17:50:45 GMT+0200 (CEST),
     size_bytes: 122155635,
     size: '116.5 mb' },
  change: 
   { size_bytes: 113535139,
     size: '108.28 mb',
     freed_nodes: 9459,
     allocated_nodes: 894338,
     details: 
      [ [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object] ] } }
00000000000008b5155e456c27eb2f51b01232090b35b189f973d37d91a45d90 183003 vel 0.2 b/s 50.17684993255026% synced
HEAP_DIFF
{ before: 
   { nodes: 943639,
     time: Fri Jul 10 2015 17:50:56 GMT+0200 (CEST),
     size_bytes: 122369747,
     size: '116.7 mb' },
  after: 
   { nodes: 1054055,
     time: Fri Jul 10 2015 17:52:34 GMT+0200 (CEST),
     size_bytes: 129776757,
     size: '123.76 mb' },
  change: 
   { size_bytes: 7407010,
     size: '7.06 mb',
     freed_nodes: 40575,
     allocated_nodes: 150994,
     details: 
      [ [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object] ] } }
00000000000004e015fb8f05cba8f9a25d9fa958818b160132038ad717b68b8a 183004 vel 0.2 b/s 50.1771241184922% synced
HEAP_DIFF
{ before: 
   { nodes: 1054296,
     time: Fri Jul 10 2015 17:52:53 GMT+0200 (CEST),
     size_bytes: 129808437,
     size: '123.79 mb' },
  after: 
   { nodes: 1053689,
     time: Fri Jul 10 2015 17:53:53 GMT+0200 (CEST),
     size_bytes: 128698681,
     size: '122.74 mb' },
  change: 
   { size_bytes: -1109756,
     size: '-1.06 mb',
     freed_nodes: 65874,
     allocated_nodes: 65268,
     details: 
      [ [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object] ] } }
00000000000003c2fc56f313b9a402ab34a8bedefc36471a0114534f70854237 183005 vel 0.2 b/s 50.17739830443414% synced
HEAP_DIFF
{ before: 
   { nodes: 1053866,
     time: Fri Jul 10 2015 17:54:11 GMT+0200 (CEST),
     size_bytes: 128728785,
     size: '122.77 mb' },
  after: 
   { nodes: 1088104,
     time: Fri Jul 10 2015 17:55:10 GMT+0200 (CEST),
     size_bytes: 130991328,
     size: '124.92 mb' },
  change: 
   { size_bytes: 2262543,
     size: '2.16 mb',
     freed_nodes: 31297,
     allocated_nodes: 65536,
     details: 
      [ [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object],
        [Object] ] } }

**Comment by pnagurny** [comment]
Hi pakar, I was running into the same issue myself with the memory increasing from several hundred megabytes to over 1GB. I captured heap dumps at various times while it was running, and they all tended to be 200 MB or less. So for some reason the stack memory size is much greater than the heap size, and I haven't figured out why yet.

The blockchain cache itself (which gets initialized from the block headers) is only around 100 MB or so for  a fully synced node. There's also a block cache which stores the last 100 blocks in memory. (lib/node.js Line 125). You can change this to a smaller number to reduce the size of that cache.

**Comment by braydonf** [comment]
Cache has been removed in: https://github.com/bitpay/bitcore-node/pull/197
