### ISSUE TITLE
Can's sync. Cannot read property 'isPublicKeyHashOut' of null

### ISSUE THREAD

**Issue by yangit** [bitpay/bitcore-node#84]
Hi,
I have setup a bitcoin node, let it fully sync, install bitcore-node and try to sync it as well.
After running for a week it stalls at block height 265458 then it gives following error in error log.

https://gist.github.com/yangit/caab3297873ff17b791c

I did that twice and had same error at same block height.
Any ideas?

**Comment by braydonf** [comment]
Try pulling in the latest changes, there is a recent commit with a patch: https://github.com/bitpay/bitcore-node/commit/23c3082ff701f1bb0705f6a63aae5291511d7115

**Comment by braydonf** [comment]
Also, we're currently working on [bitcoind.js](https://github.com/bitpay/bitcoind.js) that will dramatically improve sync times, plus a number of other benefits as we have native bindings directly to Bitcoin Core in Node.js.
