### ISSUE TITLE
[Error: Bitcoin Core JSON-RPC: host=127.0.0.1 port=8332: Request Error: connect EADDRNOTAVAIL]

### ISSUE THREAD

**Issue by ser** [bitpay/bitcore-node#85]
During syncing, after a while, I am getting:

```
[Error: Bitcoin Core JSON-RPC: host=127.0.0.1 port=8332: Request Error: connect EADDRNOTAVAIL]
network monitor disconnected
```

and syncing is being stopped, indeed. How can I convince bitcore-node to restore the connection without shutting down and starting it again?

**Comment by braydonf** [comment]
Hi @ser, we're working on running Bitcoin Core within the same Node.js process ( https://github.com/bitpay/bitcore-node/issues/57 ) with [bitcoind.js](https://github.com/bitpay/bitcoind.js/). In that case, connecting via JSON-RPC isn't needed for syncing, getting blocks is around 20 times faster, and should resolve issues such as these.

**Comment by braydonf** [comment]
The master branch now includes Bitcoin Core running within the same process.
