### ISSUE TITLE
Endpoints being cached?

### ISSUE THREAD

**Issue by luxi-io** [bitpay/bitcore-node#86]
When making a request to the /addresses or /addresses/utxos endpoint - results are cached for a considerable amount of time, making them all but useless for a real-time application. The ?noCache flag from Insight is no longer present, has this been changed, or is there a way to disable caching of these endpoints in general?

**Comment by braydonf** [comment]
This issue may be a bit outdated now, there currently isn't any caching at this point, however the updated insight-api will have limited caching.
