### ISSUE TITLE
recent master does not configure, ./configure: line 21859: syntax error near unexpected token `QTPLATFORM,'

### ISSUE THREAD

**Issue by ser** [bitpay/bitcore-node#91]
```
checking whether to compile as daemonlib... yes
./configure: line 21859: syntax error near unexpected token `QTPLATFORM,'
./configure: line 21859: `        PKG_CHECK_MODULES(QTPLATFORM, Qt5PlatformSupport, QT_LIBS="$QTPLATFORM_LIBS $QT_LIBS")'
make V=1
make: *** No targets specified and no makefile found. Stop.
```

**Comment by braydonf** [comment]
We've recently updated the README with detailed build instructions, can you check those and make sure that this doesn't resolve the issue?

**Comment by ser** [comment]
Hi, yes, thanks, I can confirm that missing dependency was ```pkg-config```, now it configures correctly.

**Comment by bharadwaja2000** [comment]
> We've recently updated the README with detailed build instructions, can you check those and make sure that this doesn't resolve the issue?

I am getting this issue after ./configure, Could you help me to fix that
