### ISSUE TITLE
txmon mempool dysync

### ISSUE THREAD

**Issue by yifuguo** [bitpay/bitcore-node#92]
calling `getTransaction` inside `daemon.on('tx', function(txid)` will always fail.

this is because the said transaction is yet to enter the mempool. unsure if this is working as intended or a bug.

**Comment by braydonf** [comment]
It's a bug, this event can include the entire transaction as a part of the data (currently only gives the txid) and/or we could also have this event happen after the transaction has been accepted into the mempool, and able to be queried via `getTransaction`, `getOutputs` and others.

**Comment by yifuguo** [comment]
ACK.

I think it is better for design if the event include the entire transaction as the callback AND at the same time call this after the transaction has been processed, whether it gets accepted into mempool or not. to better handle edge cases such as the transaction is double spend or doesn't fit certain rules to be included in the mempool.
